### ISSUE TITLE
Unable to add to playlists from app

### ISSUE THREAD

**Issue by kubo6472** [lamarios/clipious#10]
...and subscription shows error:

![Screenshot_20230305-124906_Clipious](https://user-images.githubusercontent.com/26146502/222958646-af4f610f-7b68-4d80-9502-13dd4db29eaa.png)
![Screenshot_20230305-124912_Clipious](https://user-images.githubusercontent.com/26146502/222958648-ed9ee9f7-1747-465b-9ce0-df1dec247e5a.png)
![Screenshot_20230305-124916_Clipious](https://user-images.githubusercontent.com/26146502/222958650-15dd0898-a099-4ef4-856a-468e1bd9f110.png)

**Comment by lamarios** [comment]
Is your invidious instance public? If yes do you mind sharing the url?

**Comment by kubo6472** [comment]
https://yt.tjm.sk (not public, reg disabled)

**Comment by lamarios** [comment]
Any way you could allow registration temporarily?

**Comment by lamarios** [comment]
![image](https://user-images.githubusercontent.com/1192563/222960907-1ce0dd6f-ac56-48ab-a65c-038f487723ab.png)
the popular list looks to be similar to what is in the app. So no problem here.

**Comment by kubo6472** [comment]
> ![image](https://user-images.githubusercontent.com/1192563/222960907-1ce0dd6f-ac56-48ab-a65c-038f487723ab.png) the popular list looks to be similar to what is in the app. So no problem here.

Oh, that's coincidentally my subscription list 😅

**Comment by kubo6472** [comment]
Should be enabled

**Comment by lamarios** [comment]
Thanks.

That's a strange one. I don't have issue with your server. I subscribed to all the channels in the popular section thinking there might be a video with missing data in the api but I didn't have problem

![Screenshot_20230305-212736.png](https://user-images.githubusercontent.com/1192563/222963371-528dad78-2bff-4bd9-a066-e613fc529c19.png)

No issue with playlists either. 

![Screenshot_20230305-212858.png](https://user-images.githubusercontent.com/1192563/222963395-bcd44d5f-e3b0-43a3-8616-5c91f50be02b.png)

**Comment by kubo6472** [comment]
![Screenshot_20230305-144422_Clipious](https://user-images.githubusercontent.com/26146502/222964509-8b9074ab-03c5-4103-b842-a18215c34261.png)
![Screenshot_20230305-144453_Clipious](https://user-images.githubusercontent.com/26146502/222964511-e6139da6-971d-4b35-8ed9-d0934c1b4c91.png)
![Screenshot_20230305-144502_Clipious](https://user-images.githubusercontent.com/26146502/222964512-26213229-5302-40a2-a123-8dea030ae6df.png)
![Screenshot_20230305-145054_Clipious](https://user-images.githubusercontent.com/26146502/222964513-c84f57e9-0445-4e33-ba1b-709968627dc4.png)
![Screenshot_20230305-145058_Firefox](https://user-images.githubusercontent.com/26146502/222964514-1a0e1341-f855-4c24-9036-e9fa4ecf7fc3.png)

Now it seems to be working, apart from adding videos to playlists in the app. Online it works.

**Comment by lamarios** [comment]
OK. Good to hear. I'll check the add to play list on your server tomorrow. I noticed your server isn't at the last version. Not sure if it can cause problems.

**Comment by kubo6472** [comment]
> OK. Good to hear. I'll check the add to play list on your server tomorrow. I noticed your server isn't at the last version. Not sure if it can cause problems.
> 
> Edit: I managed to reproduce. I'll look into It when I have time.

Okay, I deploy invidious from truecharts, will look into it. Thanks

**Comment by lamarios** [comment]
I see you updated your server,  I tested with debugger and it actually works now. Can you try to log in again via the app (settings -> manage server ->tap server -> login). It should do the trick, that's what i did on my phone with your server

**Comment by kubo6472** [comment]
Works now, thanks
