### ISSUE TITLE
Public server lists will not show if certain servers blocked by client-side

### ISSUE THREAD

**Issue by kowith337** [lamarios/clipious#111]
For example, I've setup pDNSF with custom hosts to block unfriendly instances, e.g. where it's behind `CloudFlare`, such as `lunar.icu`

As for that reason, this app will fail to list all instances since certain instances cannot be reached, I have no other choice than manually input correct instance in custom list one by one.

I expected that it should still showing rest of instances that still reachable, other than that it will show status number and cannot be selected by users, or removed from instance lists if user cannot connect to...

**Comment by lamarios** [comment]
fixed in version 1.7.2
