### ISSUE TITLE
F-Droid submission

### ISSUE THREAD

**Issue by offa** [lamarios/clipious#122]
How about submitting the project to [F-Droid](https://f-droid.org/)?

### Additional information

- [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/)
- [How to submit](https://f-droid.org/en/contribute/#submit-applications)

**Comment by lamarios** [comment]
Yeah I've been thinking about it. But it feels quite complicated so I've been putting it off. It's on my road map, just can't promise when.

**Comment by offa** [comment]
A first step would be a fastlane structure. After this (and with your approval) I can file a packaging request and maybe can give the packing a try (I'm not an expert in this though).

**Comment by lamarios** [comment]
I already have fast lane set up for google store publication.
I'll see if there's any resource online for fast lane and fdroid.

**Comment by offa** [comment]
> I'll see if there's any resource online for fast lane and fdroid.

https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure :-)

**Comment by lamarios** [comment]
MR here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12912
I'll add the meta data later

**Comment by offa** [comment]
Thanks! It's on F-Droid already: https://f-droid.org/app/com.github.lamarios.clipious
