### ISSUE TITLE
feature request: auto select best instance

### ISSUE THREAD

**Issue by momobobe** [lamarios/clipious#128]
Hello, I request a feature of auto selecting the best available instance/server, with balance between bandwidth (usually more important to eliminate midway loading) and latency. This could be very helpful for people living in regions with strict Internet censorship or simply poor Internet service. We may set this switchable option default so user experience would improve greatly in the said scenario.

Several ideas for the triggering mechanism (great already if any one implemented):

1. Trigger upon opening the app. Load first with the instance used last time or local cache, to avoid long-time waiting for test.

2. Trigger when the current instance is inaccessible. In this way, always load with the previously used instance first, unless it's inaccessible.

3. Trigger when loading is too slow or choppy. Accessible connection doesn't always lead to successful loading, so if loading a page or video becomes annoying, promote the user to retry or trigger the test for a better instance.

4. Trigger regularly. Maybe someone wants to test for every few hours or days.

**Comment by lamarios** [comment]
While I understand the use case, i think it might be pretty complicated to put in place.
