### ISSUE TITLE
Just asking

### ISSUE THREAD

**Issue by GET100PERCENT** [lamarios/clipious#133]
Isn't clipious on Google play store against Google's policy? I mean other foss YouTube players such as newpipe and libretube aren't present in playstore due to some policy restriction, Isn't it applicable to clipious?

**Comment by lamarios** [comment]
Yeah I guess it is against their policy, but I saw there's already an app that wraps itself around invidious' web ui so I just tried my luck.

**Comment by GET100PERCENT** [comment]
Okay

**Comment by lamarios** [comment]
well, it was removed :)
