### ISSUE TITLE
feature req. viewing responses to comments (local)

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#14]
Doesn't work without an account

**Comment by lamarios** [comment]
![Screenshot_20230308-094543](https://user-images.githubusercontent.com/1192563/223598072-65ff2522-ab4f-41e4-9239-db0317751959.png)

looks like it work. I don't have an account on this instance

**Comment by lamarios** [comment]
maybe a problem with the instance itself, i will close this issue
