### ISSUE TITLE
Android TV Playlists

### ISSUE THREAD

**Issue by Outlet7493** [lamarios/clipious#150]
Add support for playlists on Android TV as they seem to be missing from the UI. 

Could a refresh button (to reload any new videos added to playlist) also be added to the UI when you are inside of a playlist?

**Comment by WardPearce** [comment]
> Add support for playlists on Android TV as they seem to be missing from the UI.
> 
> Could a refresh button (to reload any new videos added to playlist) also be added to the UI when you are inside of a playlist?

Facing the same issue here.

**Comment by Outlet7493** [comment]
If I get some time I can try to implement an initial version of this

**Comment by Outlet7493** [comment]
![PlaylistView](https://github.com/lamarios/clipious/assets/122801553/b4244550-d79d-42e7-bc33-4700382b38aa)
![InnerPlaylistView](https://github.com/lamarios/clipious/assets/122801553/32114256-3cb5-40ee-b85a-6244cc8fa6ec)

How does this look?

Quite basic functionality at the moment (no removing videos from playlists - still working out an elegant way to do this) but allows you to use playlists on TV at least.

**Comment by lamarios** [comment]
This looks great!

**Comment by WardPearce** [comment]
yea looks great! I wouldn't be too worried about having complete functionality but as long as videos can auto play in playlists would be great.

**Comment by lamarios** [comment]
I agree. I think we should focus on playing media on TV. Management comes second.

**Comment by Outlet7493** [comment]
Will send PR in a minute.

To refresh the videos in a playlist, you will need to go back to the home screen and back into the playlists screen.

**Comment by Outlet7493** [comment]
> as long as videos can auto play in playlists would be great. 

Sorry just seen this. Currently this won't add all videos to the queue but I can try to implement this at some point. :frowning:

**Comment by WardPearce** [comment]
I'd love to contribute but my dart knowledge is extremely limited lol.

Would it be possible to include playlists in search results too?

**Comment by lamarios** [comment]
Flutter is actually pretty easy to learn.

**Comment by WardPearce** [comment]
> Flutter is actually pretty easy to learn.

Yea Flutter is on my list of languages to learn. After my current project I'll look at contributing to this repo & learning dart.
