### ISSUE TITLE
Clipious not working with certain Invidious instances

### ISSUE THREAD

**Issue by Mrnofish** [lamarios/clipious#158]
Apologies if this is a known issue: I cannot get Clipious to load anything from certain servers.

The two I've been having problems with are yewtu.be and invidious.nerdvpn.de

Both work fine in my browser. Is this a known issue?

**Comment by Outlet7493** [comment]
`yewtu.be` will not work as they have disabled the API and it will always return a 429.
`invidious.nerdvpn.de` seem to have disabled the Popular tab however I can load everything else.

You can find a full list of instances [here](https://api.invidious.io/) (which also shows API access)

**Comment by Mrnofish** [comment]
Thanks for clearing that up!
