### ISSUE TITLE
Feature: Sort search results

### ISSUE THREAD

**Issue by AceDenghar** [lamarios/clipious#166]
Hi,

Would it be possible to add the possibility to sort search results ?

It could be done by dates, views, etc...

Thanks !

**Comment by lamarios** [comment]
Yeah this needs to be added, the search needs some work as  it won't load more results for now

**Comment by lamarios** [comment]
Looks like invidious API i doesn't react to the sort parameters. I'll raise an issue there Meanwhile I'm working on fixing the search to make it better.

**Comment by AceDenghar** [comment]
Hi,

Any news ?

By the way, you done a great job ! 👍

**Comment by lamarios** [comment]
will be in next release.

**Comment by AceDenghar** [comment]
Thank you !!!! :)

**Comment by lamarios** [comment]
you can thank  @EgidioCaprino  :)

**Comment by lamarios** [comment]
won't be in 1.17.6, but should be in the following one
