### ISSUE TITLE
support for two new buttons as in newpipe

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#18]
![338377.jpg](https://user-images.githubusercontent.com/113500363/223224547-7247dd20-1327-4fac-821d-be5605bbe29b.jpg)
One button has three modes - song repeat, playlist repeat, return to no repeat mode. The second button closes the notification.

addition. I noticed that it is impossible to listen to music because of several buttons (It only rewinds for 10 seconds, that's awful), so do what I ask below. the <- and -> buttons should work as in newpipe.
https://user-images.githubusercontent.com/113500363/225999891-d32e1d22-5b45-45d2-a8e3-b53e001f4d85.mp4

**Comment by lamarios** [comment]
Probably won't be done in the near future. I'm using a library that handles this and it's handling of playlists is not great. I'd have to either modify the library or re-do the player using a more barebone player and implement all the options myself.
