### ISSUE TITLE
Subscription management not working

### ISSUE THREAD

**Issue by Patriot2407** [lamarios/clipious#189]
I cannot subscribe or unsubscribe in the app, in the readme.md it states subscription management. I have to open chrome and manage subscription there

**Comment by apprehensions** [comment]
Are you logged in? You can log in to your instance by managing it from the app.

**Comment by lamarios** [comment]
The subscription management for now is only sub / unsub from a video or channel screen.  There's no subscription management dedicated screen yet.

**Comment by midasvo** [comment]
> The subscription management for now is only sub / unsub from a video or channel screen. There's no subscription management dedicated screen yet.

Im logged into an instance but the button doesn't work for me. No feedback either. Trying it from the screen while a video is playing

**Comment by lamarios** [comment]
Can you provide screenshot of your server config screen and another one of a channel screen ?

**Comment by gi-yt** [comment]
[Screencast from 2023-06-08 19-01-52.webm](https://github.com/lamarios/clipious/assets/73596856/fd06b127-08e4-4612-9bf8-e88ce09020ec)

**Comment by gi-yt** [comment]
https://github.com/lamarios/clipious/assets/73596856/23d6c4f7-aa74-4390-b2ce-e2b89c5279e6

**Comment by gi-yt** [comment]
![Screenshot_20230608-191451](https://github.com/lamarios/clipious/assets/73596856/13bd1013-5218-4502-9baa-804a9ae0742c)

**Comment by lamarios** [comment]
I'll publish an update this week end where user can retrieve logs and see if it there is something useful there

**Comment by PtPhoenix** [comment]
I have the same problem:

[INFO] [Service] - 2023-06-17 22:59:16.316 - Response from GET https://xxxxxxxxxx/api/v1/stats, status: 200

**Comment by noideas4thisname** [comment]
Popping in to note that I'm having the same problem as well. Attempting to hit the subscribe button from anywhere does nothing, and looking at the logs I get the same 200 responses as @PtPhoenix.

**Comment by yo-hansolo** [comment]
Have exactly the same problem with 1.11.0
I'm logged in on my instance and impossible to add a subscription. The button never change to validate my choice.
On the log page there are, like others, response status 200 to API but nothing in my subscription tab.
Strange behavior.

**Comment by lamarios** [comment]
I figured the issue. Somehow subscribing might return a "channel doesn't exist" response from invidious. It can work again after a while of spamming the endpoint. 

The only way is to brute force retry until it works. I'll add this in next release.
