### ISSUE TITLE
Add application icon

### ISSUE THREAD

**Issue by amokiel** [lamarios/clipious#2]
This application experience is very convenient, I think it has great potential.
However, it is not used to the application without icons.
I hope the author can continue to develop this application.I believe that in the future at least thousands of stars.
Thank you for your hard work.

**Comment by lamarios** [comment]
Hi. Thanks for the interest. I'm already working on an icon :) that's my goal for the week.

**Comment by lamarios** [comment]
Icon available in the latest version.
