### ISSUE TITLE
Show more descriptive error message when adding a private server

### ISSUE THREAD

**Issue by ddscentral** [lamarios/clipious#202]
Hi there.

I have set up a private instance of Invidious which streams everything over a VPN proxy. For obvious reasons, I do not wish to make this instance public so I run it behind a reverse proxy with basic authentication.
But there doesn't seem to be a way to use basic authentication in Clipious, the server is rejected outright. 

The server works fine with Clipious if authentication is disabled.

**Comment by lamarios** [comment]
Have you tried authenticating with the cookie method ? I think this should work. Someone had a similar problem which is why  I added this authentication method, i'm trying to find back the issue.

**Comment by lamarios** [comment]
see #54

**Comment by ddscentral** [comment]
Cookie does work for authenticating invidious user. But not for authenticating to the main page which has basic authentication (handled by the front proxy).

**Comment by lamarios** [comment]
See the issue, you should use the following for your instance url:
```
https://username:password@your_invidious_domain.com/.
```

**Comment by ddscentral** [comment]
Thanks, that seems to work.
It would be helpful to change the error message when adding a new server to instruct the user to use the user:pass URL format if basic authentication is detected.

**Comment by rhyst** [comment]
Hello,

I am also trying to get this working with basic authentication. I can log in with the cookie method but all of the authenticated endpoints fail.

I.e. if I attempt to access the subscriptions page then I get the "Could not fetch videos" error and in my invidious logs I can see that it has responded with a 403:

```
403 GET /api/v1/auth/playlists
```

**Comment by rhyst** [comment]
Ah it turns out that if you are reverse proxying with basic auth then you need to strip the Authorization header before the request reaches invidious, otherwise I guess it uses that rather than the cookie. This all seems to work now.

**Comment by rhyst** [comment]
Apologies for spam but that did not actually allow the videos to play. I think because the app gets image links and manifest links from the api it attempts to load them without basic auth, so I see logs like:
```
401 my-server/vi/someid/maxres.jpg401 
401 my-server/api/manifest/dash/id/someid
```
By excluding the paths `vi` and `api/manifest` from basic auth then the videos play properly.
