### ISSUE TITLE
Arabic language used by default when no translations are found.

### ISSUE THREAD

**Issue by ddscentral** [lamarios/clipious#203]
Hello there.
When Android system language (in my case it's Lithuanian) does not match any of the translations in Clipious, it uses Arabic as the default language. My guess it's because it's the first language in the list. 
English would be a much better choice as the default language when no translations exist for the current system language.

**Comment by lamarios** [comment]
hmm strange, I'll look into it, thanks for the report

**Comment by lamarios** [comment]
Ok I tried to reproduce it but I can't make it happen. Which android version are you using ?

**Comment by lamarios** [comment]
Fixed in version 1.8.7
