### ISSUE TITLE
Can't Add Videos to Playlist

### ISSUE THREAD

**Issue by kmccmk9** [lamarios/clipious#206]
1. Be signed into a lemmy instance
2. Create a new playlist
3. Try long tapping a video and selecting your newly created playlist
4. See error at the bottom saying: error while adding video to playlist

Also I tried creating a new playlist instead of adding to an existing one and I received the same error. I also tried adding to playlist from the video info screen and I get the same error. Using a web browser I can add videos to said playlists just fine. The log file only shows the following:

`INFO] [Service] - 2023-06-17 03:02:00.299 - Response from POST https://xxxxxxxxxx/api/v1/auth/playlists/IVPLeDYiPx7TVMMGDthk687poSulrLnVt82/videos, status: 403 
[SEVERE] [Service] - 2023-06-17 03:02:00.302 - Error while calling service: Invalid scope`

**Comment by lamarios** [comment]
It looks like your session is lacking permissions to add to a play list. Can you try to log in with the cookie method to see if the problem still persists?

**Comment by kmccmk9** [comment]
Just following up, changing to the cookie option did fix the issue.

**Comment by lamarios** [comment]
I'm still not sure what is the issue, do you mind trying to log in again with the other method and showing me a screenshot of the invidious page when it is showing the list of scopes it want to access ?

**Comment by kmccmk9** [comment]
I haven't been able to reproduce it since updating to the latest version. I'll keep poking at it and see if I can get it to happen again.

**Comment by lamarios** [comment]
I'll close this one.

**Comment by BuzzKnightbeer** [comment]
I have the same problem. I'm on a Pixel 7, private playlist. When I try to add a video to it I don't get any error messages, it just doesn't get added.  When switching to cookie login it works.

**Comment by lamarios** [comment]
most likely same problem as https://github.com/lamarios/clipious/issues/347  which i reported on invidious side : https://github.com/iv-org/invidious/issues/4200

**Comment by lamarios** [comment]
made the PR for the fix: https://github.com/iv-org/invidious/pull/4348
