### ISSUE TITLE
What's up with the logo?

### ISSUE THREAD

**Issue by mildred** [lamarios/clipious#214]
I found your app in the F-Droid store and the logo really shocked me. Do you know that the pedophile boy-lover logo is really close to your logo? See https://www.wikileaks.org/wiki/FBI_pedophile_symbols

Your logo: 

![image](https://github.com/lamarios/clipious/assets/33804/2e00936c-8518-4ba7-95b6-95691de637fb)

FBI document extract:

![image](https://github.com/lamarios/clipious/assets/33804/6cfed8f3-abef-4bd6-94cf-186196924e4f)

I'd advise you to change your logo.

**Comment by lamarios** [comment]
I obviously did not know. I'll see if I can update it to make it less similar.

**Comment by lamarios** [comment]
"Funny" enough my idea behind the logo is similar to theirs. It's a player (invidious) surrounding another one (YouTube) as the former is a proxy for the later.

**Comment by hFULAveTeR** [comment]
> "Funny" enough my idea behind the logo is similar to theirs. It's a player (invidious) surrounding another one (YouTube) as the former is a proxy for the later.

I don't think it's necessary to change the logo. If that was your intention, you don't have to worry. It would be like asking Buddhist, Hindu, etc., religions to change the Manji symbol because of its association with the Nazi swastika.

**Comment by lamarios** [comment]
new icon in next release
