### ISSUE TITLE
Landscape videos go to full screen in portrait mode

### ISSUE THREAD

**Issue by jujar** [lamarios/clipious#217]
Tapping the full screen button on a standard landscape aspect ratio video goes to full screen in portrait mode.

The expected behavior, from all other similar apps like LibreTube, NewPipe, or other video player apps, is that tapping full screen would make the screen go also into landscape mode. 

My device is Oneplus 7 Pro.
I'm using Android 13 (DivestOS).
App version is 1.8.8

Here's an unnecessary screenshot of the problem.

![Screenshot_20230624-100833_Clipious (Small)](https://github.com/lamarios/clipious/assets/56905335/1b294c3a-0375-44b4-a67a-6a640f9e8dc5)

**Comment by lamarios** [comment]
Will be in next version
![image](https://github.com/lamarios/clipious/assets/1192563/e44b91a3-2559-4cc6-a6df-099c2e0479c3)

**Comment by jujar** [comment]
Fantastic, thank you so much!
