### ISSUE TITLE
[Feature Request] Swipe to add to video queue & hide channel content

### ISSUE THREAD

**Issue by PacoBell** [lamarios/clipious#219]
I would like to have the option to quickly add any video to my video queue to be automatically played as soon as the currently playing video is complete. Right now, I only see an option to add to a playlist by long-pressing. Perhaps you could also include another gesture like swiping right to add to video queue? I'd also like to see a swipe left gesture to hide an entire channel's content from showing up in any of the feeds. Thanks so much for creating this awesome app!

**Comment by lamarios** [comment]
Next version will add video filters where you can hide videos from a channel but no quick shortcut for now though.

For play next, it will be in the next version but as a long press action.

![image](https://github.com/lamarios/clipious/assets/1192563/5d06662c-d066-4c25-976f-6d0c8df1c409)

**Comment by lamarios** [comment]
Here are the upcoming video filtering settings, after selecting a channel, it's possible to hide all videos for it.

![Screenshot_20230704_180413](https://github.com/lamarios/clipious/assets/1192563/e30c1bf6-b45b-4fcf-b08f-2a225642c6af)

**Comment by PacoBell** [comment]
Thanks for this, but wouldn't the queue make more sense as a FIFO rather than a LIFO? Also, it's way too easy to accidentally exit the app with a screen edge gesture. Could you find a way to retain the play next queue between sessions and maybe add an option to provide a guardrail prompt when exiting?

**Comment by lamarios** [comment]
Well for the queue, I implemented as a Play next, maybe i should also add a "add to queue" button. 

Keeping the queue could be an idea, I can look into that, can you create a new ticket for this.

The prompt when exiting I won't do it. I find it really annoying when apps do it.

**Comment by lamarios** [comment]
There will be a button next release to add to queue in addition to the play next button
