### ISSUE TITLE
live video broadcast. Replacing

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#22]
![338380.jpg](https://user-images.githubusercontent.com/113500363/223227580-35cc1c5e-8862-4755-9f9f-ab10081b1c85.jpg)

Write "live" instead of "0 seconds ago

**Comment by lamarios** [comment]
Can't fix, the data provided by the api is not correct.  
![image](https://user-images.githubusercontent.com/1192563/223720400-de15f701-55ce-4c11-9e32-290929d2e565.png)
