### ISSUE TITLE
Impossible to change subtitle font size on Android TV

### ISSUE THREAD

**Issue by nerdchills** [lamarios/clipious#231]
I have Clipious installed on a Chromecast w/ Android TV and am unable to increase or decrease subtitle font size. The minus and plus signs are unable to be selected.

**Comment by lamarios** [comment]
You are right, this doesn't work anymore. I'm planning to work on few TV improvements this week end, I'll try to get this fixed.

**Comment by lamarios** [comment]
Now will require to use the remote left and right button to adjust, should be in the next version

![image](https://github.com/lamarios/clipious/assets/1192563/9d92e254-3490-4ae6-b9eb-56cab549036e)
