### ISSUE TITLE
[Suggestion] Less opaque UI overlay for the video player

### ISSUE THREAD

**Issue by slashdevslashurandom** [lamarios/clipious#236]
Right now when you tap on the video player to open the UI, the overlay is incredibly dark, to the point that it is very hard to see the video.

In comparison, other apps, like NewPipe and LibreTube, don't darken the background as much -- enough to see the UI elements and the video at the same time.

I suggest bringing the opacity of the dark background in that overlay closer to that of the other apps.

**Comment by lamarios** [comment]
I'm trying to move away from the current video player library i'm using because it's abandoned and i monkey patched things on it. I'm planning on building my own controls so i can fix this as well

**Comment by lamarios** [comment]
Please check the latest version, it should be better now

**Comment by slashdevslashurandom** [comment]
Seems to me like the issue isn't fixed. Here, for example, is that UI overlaid over a Veritasium video about IQ at a moment when the video mostly consists of a white screen.
![Screenshot_20230823_150506](https://github.com/lamarios/clipious/assets/53902042/ba76ab8e-e46c-49af-9ebe-09789365e043)

**Comment by lamarios** [comment]
You're on an old version of the app. Please update to the latest.
