### ISSUE TITLE
Ability to click timestamps in description and comments

### ISSUE THREAD

**Issue by u132** [lamarios/clipious#240]
Like 9:48, 53:25, etc.

**Comment by stickyburn** [comment]
@lamarios any thoughts? If doable without major blockers I can take this up :smile:

**Comment by lamarios** [comment]
I'm not sure how doable it is but feel free to hace a crack at it. I started working on the video download part so it will take up most of my app work time for a while.

**Comment by lamarios** [comment]
@stickyburn i'm looking at some improvements on text links, i'll look into this one as well
