### ISSUE TITLE
[Feature-Request for TV] Show Video duration and faster repetitive skipping

### ISSUE THREAD

**Issue by Visiraptor** [lamarios/clipious#257]
Thanks for the nice app I am using on my AndroidTV. 
Three wishes I have for now: 

1. Showing how long the video duration is without having to open/play it (so in preview/llist/search mode). According to the screnshots it's working on phone and tablet but unfortunately not on TV (why not?).  
2.  Make it possible to skip more than 10 secons. Sometimes I want to skip (let's say) 20 Minutes but have to wait a lot since skipping goes only in 10 second steps. This could be fastened when you are doing it multiple times. Not saying that it should be setable to skip X seconds by default but the "skip longer times when holding the button". 
3. Beeing able to click the links in the video description. Needed for exaple when having "referencing" or "ongoing" series (without having to leave the "main/playing" video). For now you can read the description but not click anything in there.

Oh and a last thing that disturbs me personally (at least a bit). The "play/pause" button on my Amazon FireTV remote does not pause the video (but on all other apps it is working so it might be a "Clipious" problem). So I do have to double click the "ok"-button.

Keep up the good work. 
Have a nice sunday.

**Comment by lamarios** [comment]
Fixed all except 3 in the linked PR including media buttons if amazon follows the standard keycodes because the emulator's remote only has directional buttons + home / back

I'm not sure what you mean in the 3rd point to be honest
