### ISSUE TITLE
feature req. "in-window" feature (as in newpipe)

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#26]
it creates a small window on the screen with the video

![338394.jpg](https://user-images.githubusercontent.com/113500363/223234266-13cd8ebc-5f41-44b9-99de-b45cd81bdacc.jpg)

![338395.jpg](https://user-images.githubusercontent.com/113500363/223234267-462e10ab-f44e-467e-b052-5d56f5be7324.jpg)

**Comment by lamarios** [comment]
Fixed in v1. 3.3
