### ISSUE TITLE
Could you please change the logo ?

### ISSUE THREAD

**Issue by minou2020** [lamarios/clipious#272]
Well, to be honest, the icon doesn't look like a video player icon .
Could you please update it ?

**Comment by lamarios** [comment]
See #214. I'll change it when I have inspiration and time. If you feel offended by it. Don't use the app in the mean time an d follow issue #214.

If you have design skills please provide logo ideas.

**Comment by minou2020** [comment]
Ok

**Comment by lamarios** [comment]
New icon released
