### ISSUE TITLE
Android TV Playlist not respecting order.

### ISSUE THREAD

**Issue by WardPearce** [lamarios/clipious#277]
Playlists on Android TV tend to repeat the 1st 2 videos twice until actually respecting the playlist order

**Comment by lamarios** [comment]
is it for your own playlist or public youtube playlist ? I found a bug in my handling of the loading of public playlist videos that might lead to duplicated. Can you check with 1.14.2 to see if it was luckily fixed.

**Comment by WardPearce** [comment]
Was with public playlist, I'll validate now.

**Comment by lamarios** [comment]
the version is still releasing, give it another 10 minutes

**Comment by lamarios** [comment]
https://drone.ftpix.com/lamarios/clipious/723

**Comment by WardPearce** [comment]
Just tested, appears the 1st 2 videos are consistently not shown now at all.

**Comment by lamarios** [comment]
:thinking:

**Comment by lamarios** [comment]
if you can share a sample play list link it's look into it

**Comment by WardPearce** [comment]
Sure

https://invidious.wardpearce.com/playlist?list=PLkG-zhy1pVunBQ6heSqSoccZvxmLLuT2u

**Comment by lamarios** [comment]
ok, found the issue, it's a strange one. Getting the public playlists from invidious, will give a random number of prefetched videos, i was overriding the prefected ones. somehow the playlist i tried came with 0 vidoes to start with

**Comment by WardPearce** [comment]
yea thats very odd

**Comment by lamarios** [comment]
https://drone.ftpix.com/lamarios/clipious/726 should be in next release

**Comment by WardPearce** [comment]
Yup appears the latest version has fixed the issue 👍
