### ISSUE TITLE
Add skip ssl cert verification option on first time wizard(Android 7 SSL issues)

### ISSUE THREAD

**Issue by ThaDaVos** [lamarios/clipious#293]
**Describe the bug**

In the latest build, maybe some before that there seems to be SSL issues as the public list won't load and I couldn't connect with my private instance till I turned off the SSL check.

At least, on my Android 7 tablet, my phone with Android 13 works fine

**To Reproduce**

Check above 

**Expected behavior**

Just works

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 7a] Nvidia Shield Tablet
 - OS: [e.g. Android 13] Android 7
 - Version [e.g. 1.14.1] latest

**Additional context**

**Comment by lamarios** [comment]
So does it work if you enable the skip ssl verification ? Might be the table root certificate not up to date if it hasn't received any update for a while, especially if your instance is using let's encrypt as the root certificate changed last year.

**Comment by lamarios** [comment]
Yeah i'll need to add the skip ssl verification on the first time set-up wizard.

**Comment by ThaDaVos** [comment]
Yeah that would be really useful - as my tablet couldn't load the public list either - so getting to that setting was a little chore to do 🤣

Apparently I need a new cert which contains the extended chain: https://community.letsencrypt.org/t/production-chain-changes/150739

**Comment by ThaDaVos** [comment]
@lamarios  - as my Android 7 tablet can load the website just fine without certificate warnings - maybe the issue is inside `Clipious`?

**Comment by lamarios** [comment]
Maybe I'm not sure where does flutter gets its certificates from neither I know if your browser keeps its own certs and update it itself.

I'll make a release to move the options for skipping ssl certificates inside the server management so it can appear on the first time use set up. Other than that I'm not sure what I can do.

**Comment by ThaDaVos** [comment]
> Maybe I'm not sure where does flutter gets its certificates from neither I know if your browser keeps its own certs and update it itself.
> 
> I'll make a release to move the options for skipping ssl certificates inside the server management so it can appear on the first time use set up. Other than that I'm not sure what I can do.

Ah that's a good one - I'll check if that's the case and try to fix it on my device by adding the new root certifcate
