### ISSUE TITLE
[Feature Request] Hide populair if disabled on instance

### ISSUE THREAD

**Issue by ThaDaVos** [lamarios/clipious#294]
**Is your feature request related to a problem? Please describe.**

In Invidious one can disable the `populair` feed - but it stills shows inside the app and gives an error that it couldn't load any videos.

**Describe the solution you'd like**

Hide the feed when `populair` is disabled

**Describe alternatives you've considered**

None? 

**Additional context**

**Comment by lamarios** [comment]
I'm thinking of reorganising the main screen a bit that should be able to cater for this.

I think there are too many buttons and sections and might take some inspiration from libretube on this one. With something like Home / subscriptions / library

**Comment by ThaDaVos** [comment]
Yeah or look at how the newest Youtube UI is like perhaps
