### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [lamarios/clipious#3]
https://hosted.weblate.org/projects/clipious/#information says "Proprietary"
Should be MIT like the repo?

Can be changed in
https://hosted.weblate.org/settings/clipious/app-translation/
and
https://hosted.weblate.org/settings/clipious/glossary/

Invidious is AGPLv3-or-later, I think that is better for the network protection, but I have no say. :)

**Comment by lamarios** [comment]
Thanks updated. I'm still setting this up.
