### ISSUE TITLE
Android TV - Built in updater

### ISSUE THREAD

**Issue by WardPearce** [lamarios/clipious#302]
Would be useful if users on Android TV could easily update the app without having to do it manually through whatever channel they use. Could simply be a "Check for update" button in settings, what checks for a new Github release artifact.

**Comment by Outlet7493** [comment]
Working on it

**Comment by lamarios** [comment]
Let me discuss with accrescent on to which extend they allow auto updating.

**Comment by lamarios** [comment]
I think the best would be to have a different flavor of the app one with auto updater one without.

**Comment by lamarios** [comment]
Ok, after chatting a bit more with accrescent. maybe we hold on the auto update feature first. Accrescent is actually pretty close to work well enough on TV.

**Comment by WardPearce** [comment]
Awesome, I also put in a request for clipious to be added to apkupdater too. Accrescent TV support would be dope tho.

**Comment by Outlet7493** [comment]
What's the latest on this? I see it was requested again so just wondering as I am still happy to implement it as a button in settings.

**Comment by lamarios** [comment]
I didn't see any changes on accrescent i believe. if you're keen on contributing, go ahead, maybe only for TV though.

**Comment by lamarios** [comment]
Apparently accrescent should already be usable on TV. Let's wait for this ticket first to see if we should proceed with auto updater: https://github.com/accrescent/accrescent/issues/365

**Comment by lamarios** [comment]
After checking again the last version of accrescent works well enough to be usable on tv. I'll update the README with recommendation for TV users.
