### ISSUE TITLE
Double Tap Gesture to Advance/Reverse Seek

### ISSUE THREAD

**Issue by joseio** [lamarios/clipious#309]
### Proposed Enhancement
It would be greatly helpful if users could:
(1) enable a double tap gesture on the left and right side of a video to reverse and forward seek, respectively, by a certain number of seconds and 
(2) define how many seconds the reverse/forward seek skips in the settings 

This would just be a minor enhancement to improve usability and match the Individuous web frontend a bit more.

**Comment by lamarios** [comment]
Added the double tap in last version.

Won't add settings to define skip step though. I want to try to have too many setting as I already feel there are too many. Instead I added the same thing as the TV version of the app. The more you skip the bigger the steps are.
