### ISSUE TITLE
Adding Video to Watch History Before Reaching the 50% Mark


### ISSUE THREAD

**Issue by joseio** [lamarios/clipious#314]
### Issue 
What currently happens is that once a video is watched at least 50% of the way through, an Invidious API request is made to add the video to the logged in user's watch history. This 50% mark may be reasonable for short-form videos (i.e., those less than 10 minutes), but becomes less reasonable for longer fork videos (e.g., those longer than 1.5 hours). For longer form videos, if the user closed the app before reaching the long-form video's halfway point, they would have to manually search for the video title again and scrub to an approximate position of where they believe they left off at. 

### Potential Solution
A potential solution would be to add a video to watch history after 30 seconds - 1 minute of watching a video (providing the video, itself, is of that length or greater) so that regardless of whether the user reaches the halfway point or not, they'll be able to pick back up where they left off with ease. 

### Potential Pitfalls 
I'm not sure why the 50% mark was originally chosen to be the point where a video will be added to a user's watch history, but I suspect it may have to do with API call limits. If this is the case, I'm not certain how to account for it in the above proposed solution, but I'm open to brainstorming.

**Comment by lamarios** [comment]
the 50% mark has been arbitrarily chosen to be hones. There is no api call limit issue as it is debounced until the video playback stops.

I have nothing against changing it.
