### ISSUE TITLE
Video queue randomly skipping ahead

### ISSUE THREAD

**Issue by PacoBell** [lamarios/clipious#316]
**Describe the bug**
After queueing several videos, the queue will suddenly jump to another video down the queue. This problem seems to be exacerbated by increased playback speed. Also, while a video is paused, playback will spontaneously be unpaused and the play button will still erroneously display a paused state. Pausing again requires hitting the play button twice. Furthermore, attempting to play a previous video in the queue causes the queue position to jump ahead while the intended video plays for a short while and then eventually stops playing and skips to the highlighted video in the queue.

**To Reproduce**
1. Queue several videos.
2. For good measure, set playback speed to something like 3.0 or higher and change settings to remember playback speed.
3. Play the queue.
4. Observe the arbitrary skipping. Sometimes several queue items are skipped at once.

**Expected behavior**
Queued videos are played back in an orderly fashion and arbitrary navigation within the queue is honored.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Version: 1.15.4

**Comment by lamarios** [comment]
I noticed some weird behavior in the video queue management. I made an attempt to fix this and it will be available in the next release.
