### ISSUE TITLE
[Suggestion] Replace play/pause button with restart when video is done playing

### ISSUE THREAD

**Issue by Mrnofish** [lamarios/clipious#318]
**Is your feature request related to a problem? Please describe.**
When a video is done playing, the play button is displayed in the middle of the video frame. Touching the button achieves nothing because the video is already at the end. It is thus necessary to bring the slider back to the start and then press the play button.

**Describe the solution you'd like**
When the video is done playing, replace the play button with restart, which brings the cursor back to the start of the video and then triggers playback.

**Comment by lamarios** [comment]
will be in next release
