### ISSUE TITLE
feature req. Next to likes or creation time show the number of views

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#32]
![338566.jpg](https://user-images.githubusercontent.com/113500363/223402410-8331e00a-8542-4401-8677-a565313a2b66.jpg)

**Comment by lamarios** [comment]
Code is [there to show](https://github.com/lamarios/clipious/blob/master/lib/views/video/info.dart#L43) it but api doesn't always provide it somehow. Please raise an issue iwth invidious.
