### ISSUE TITLE
allow background for subtitles and/or black text 

### ISSUE THREAD

**Issue by ChuckBartowski91** [lamarios/clipious#323]
**Is your feature request related to a problem? Please describe.**

Hello. Since the subtitles are in white without background they mix with the video and even using a large font sometimes text is hard to read. 

**Describe the solution you'd like**

I would like a background as invidious on the web and/or black fonts. Thanks.

**Describe alternatives you've considered**
No one I can think of.

**Comment by lamarios** [comment]
I added a small black outline by default on subtitles, will be available in 1.16.3. Let me know how it is.

**Comment by ChuckBartowski91** [comment]
> I added a small black outline by default on subtitles, will be available in 1.16.3. Let me know how it is.

I coukd be wrong but maybe it's not working because I can't see the difference.

**Comment by lamarios** [comment]
Added settings for next release, whenever that will be.
