### ISSUE TITLE
Videos not playing, no thumbnails visible

### ISSUE THREAD

**Issue by lead0r** [lamarios/clipious#331]
I have a local Invidious instance (no https/only visible on local network) that works very fine in the browser. 
In Clipious, I can add the server and log in with a token.
I see all videos listed, but without any thumbnail (just an exclamation mark in the middle) and cannot play any video. Youtube profile pictures are visible.

I tried with and without DASH and with and without "skip ssl verification".

I know this is the clipious github page and I am posting this on here because Invidious in the browser works just fine, but I am attaching my Invidious docker-compose.yml because that is the only thing I adjusted myself. I uploaded a zip, because I am too dumb to use markdown for adding the yaml directly and .yml is not a supported file format to upload
[docker-compose.yml.zip](https://github.com/lamarios/clipious/files/12792580/docker-compose.yml.zip)

**Comment by lamarios** [comment]
If you don't see thumbnails. Check this link: https://github.com/lamarios/clipious/wiki/Common-Issues#video-thumbnails-not-working

**Comment by lead0r** [comment]
> If you don't see thumbnails. Check this link: https://github.com/lamarios/clipious/wiki/Common-Issues#video-thumbnails-not-working

Thank you, that worked. Added port 80 and domain with my local ip and port
