### ISSUE TITLE
History in Home does not show any videos

### ISSUE THREAD

**Issue by update-freak** [lamarios/clipious#332]
**Describe the bug**
In the home screen there is the message "Daten konnten nicht abgerufen werden" instead of showing the last viewed videos:
![Screenshot_20231003_204257](https://github.com/lamarios/clipious/assets/40196995/908b0032-8e28-472a-96bb-a00bdd540a8e)

**To Reproduce**
Set history in the home screen

**Expected behavior**
Overview of last viewed videos

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23
 - OS: Android 13
 - Version: 1.16.3

**Comment by lamarios** [comment]
Are you logged in to your instance?  History requires to be logged in to work. 

If yes Have you been using the app for a long time? (before history was actually a thing)

If yes try log in an dout again if you logged in using the token method or try logging in with the cookie method.

**Comment by update-freak** [comment]
I was not logged in, so that was the problem.
Thanks for the quick answer.
