### ISSUE TITLE
Refresh Rate Drops from 120Hz to 60Hz When Opening the App

### ISSUE THREAD

**Issue by myNicole98** [lamarios/clipious#339]
**Summary:**

When I open the app on my smartphone, the device's refresh rate drops from 120Hz to 60Hz, causing a noticeable decrease in smoothness and responsiveness. This issue seems to be specific to this app and doesn't occur with other apps or the phone's default settings.

**Steps to Reproduce:**

- Open the app on a smartphone with a 120Hz refresh rate display.
- Observe that the smartphone's refresh rate drops to 60Hz upon opening the app.
- Close the app, and the refresh rate returns to 120Hz.

**Device Model:** 

Realme GT Neo 2

**Additional informations:**

This issue seems to be caused by a bug in flutter: https://stackoverflow.com/questions/63631522/flutter-120fps-issue#63632461

**Comment by lamarios** [comment]
Can try this apk ? 
[app-arm64-v8a-release.zip](https://github.com/lamarios/clipious/files/12903431/app-arm64-v8a-release.zip)

**Comment by myNicole98** [comment]
Yup, now it's working properly!

**Comment by lamarios** [comment]
awesome, i'll add this the the next release then
