### ISSUE TITLE
thumbnails do not appear with the self-hosted instance

### ISSUE THREAD

**Issue by tribeiros** [lamarios/clipious#342]
I add my self-hosted instance, and I'm able to use it normally, and everything works fine,
but the video thumbnails don't appear, just an exclamation mark

**Comment by lamarios** [comment]
https://github.com/lamarios/clipious/wiki/Common-Issues

Does that help?

**Comment by tribeiros** [comment]
Yes, I configured the domain and external_port environment variables and everything worked correctly

**Comment by lamarios** [comment]
I'll close the issue if its working then.
