### ISSUE TITLE
Playlist videos in queue aren't autoplaying

### ISSUE THREAD

**Issue by WardPearce** [lamarios/clipious#346]
When playing a whole playlist via clicking the big play button, it shows the videos in queue but it only loops the 1st video and doesn't play the rest.

**Comment by stickyburn** [comment]
Hi again @lamarios! Do you think this is a good for beginner bug?

**Comment by lamarios** [comment]
i managed to reproduce locally but some how it works fine on my emulator. It might be a bit difficult for a beginner. I'm currently looking into it.

**Comment by lamarios** [comment]
ok found the issue, it was a race condition when setting the playing video sponsor block segments that would overwrite the play next queue. Fix will be in next release
