### ISSUE TITLE
"Subscribe" button not working.

### ISSUE THREAD

**Issue by knightking21** [lamarios/clipious#347]
**Describe the bug**
Clicking on the "Suscribe" button is not adding the channel to subscription and just keeps loading infinitely 

**To Reproduce**
1. Go to Any Channel Page
2. Click on "Subscribe" button

**Expected behavior**
As soon as the "Subscribe " button is clicked, it should add the channel to the subscriptions after loading for some time.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Tecno Spark 6 Air
 - OS: Android 10
 - Application Version 1.17.0

**Additional context**
Application Logs:
[INFO] [Service] - 2023-10-16 06:52:34.918 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:35.723 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:35.730 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:35.737 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:35.742 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:36.059 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:36.065 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:36.079 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:36.085 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:38.919 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:38.927 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:38.936 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:38.943 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:39.882 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:39.889 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:39.896 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:39.900 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:40.850 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:40.857 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:40.867 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:40.873 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:41.254 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:41.261 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:41.280 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:41.286 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:41.664 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:41.669 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:41.682 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:41.686 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions/UCgpMZXjo2rbt5YtaorTw_EA?local=true 
[INFO] [Service] - 2023-10-16 06:52:42.069 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:42.073 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:42.118 - 403 - {"error":"Invalid scope"} 
[INFO] [Service] - 2023-10-16 06:52:42.141 - calling https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true 
[INFO] [Service] - 2023-10-16 06:52:42.585 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 
[INFO] [Service] - 2023-10-16 06:52:42.601 - Response from GET https://xxxxxxxxxx/api/v1/auth/subscriptions?local=true, status: 200 

Server Used:- https://vid.priv.au
(It's same for all other servers)

**Comment by WardPearce** [comment]
same issue while unsubscribing too

**Comment by lamarios** [comment]
Can you take a screen shot of the instance log in when it shows the scope when using the token method ? This the screen after you type in username and password  where it shows the scopes and ask yes or no.

Try logging in with username / password (cookie method) and see if it works.

**Comment by UlyssesZh** [comment]
I can reproduce this bug. I was just about to open an issue and saw this issue.

> Try logging in with username / password (cookie method) and see if it works.

Yes, logging in with password works.

**Comment by knightking21** [comment]
> Can you take a screen shot of the instance log in when it shows the scope when using the token method ? This the screen after you type in username and password where it shows the scopes and ask yes or no.

Here the Screenshots... I have Logged out and then Logged in again using the Token Method (Hope they are the right ones)
![image](https://github.com/lamarios/clipious/assets/73683964/363aa069-f994-4c10-b6ca-5da1f5ed49e6)
![image](https://github.com/lamarios/clipious/assets/73683964/22069cb4-9228-40e8-91a9-dab5e1654eb3)
![image](https://github.com/lamarios/clipious/assets/73683964/8faa8431-4706-4969-8951-0284454c2873)

> Try logging in with username / password (cookie method) and see if it works.
Yes, it works!

**Comment by lamarios** [comment]
for the screen shot, i was asking for this:
![Screenshot_20231017-100833~2](https://github.com/lamarios/clipious/assets/1192563/31d7801d-e56e-4588-aed5-af03c90b2a09)

This screen should show up when logging in using the token method.

**Comment by knightking21** [comment]
Sorry for my mistake...

Here's the screenshot :

![Screenshot_20231017-185948.png](https://github.com/lamarios/clipious/assets/73683964/5e1cd95e-5e51-4c77-92e2-36ed26c19b08)

**Comment by ViktorKahu** [comment]
Unable to:

- subscribe
- unsubscribe
- add to play list
- remove from play list

**Comment by lamarios** [comment]
are you using a public instance ? if yes , please share it with me so I can test

**Comment by ViktorKahu** [comment]
https://invidious.perennialte.ch

**Comment by ViktorKahu** [comment]
> Unable to:
> 
> * subscribe
> * unsubscribe
> * add to play list
> * remove from play list
> * create play list
> * delete play list
> * download

I would like to confirm that all of the above works when signed in to the website (via the browser) using a token, but not through the clipious app.

**Comment by ahmadyusuf** [comment]
I am having the same issue when using the Token login method.

But if I switch to Cookie method, the subscribe / unsubscribe is working fine

**Comment by lamarios** [comment]
I think I managed to reproduce the issue.
if I'm not logged in on the website on my browser beforehand and using the token method the scopes are wrong (missing the *). If I am already logged on the website and log in with token. The scopes seem correct.

**Comment by ViktorKahu** [comment]
> I think I managed to reproduce the issue. if I'm not logged in on the website on my browser beforehand and using the token method the scopes are wrong (missing the *). If I am already logged on the website and log in with token. The scopes seem correct.
> 
> That looks like an issue with invidious. Will investigate further and raise it to them if that's the case.

Thanks for your efforts, I can confirm your findings.

1) Sign out of Clipious
2) Sign into website, do not close the browser.
3) Sign into Clipious using token.

Works beautifully.

**Comment by lamarios** [comment]
Submitted the issue here: https://github.com/iv-org/invidious/issues/4200

**Comment by lamarios** [comment]
PR for fix on invidious: https://github.com/iv-org/invidious/pull/4348

**Comment by lamarios** [comment]
My PR on invidious was finally merged and available on invidious. I'll close this.

**Comment by cameronj86** [comment]
> > I think I managed to reproduce the issue. if I'm not logged in on the website on my browser beforehand and using the token method the scopes are wrong (missing the *). If I am already logged on the website and log in with token. The scopes seem correct.
> > 
> > That looks like an issue with invidious. Will investigate further and raise it to them if that's the case.
> 
> Thanks for your efforts, I can confirm your findings.
> 
> 1) Sign out of Clipious
> 2) Sign into website, do not close the browser.
> 3) Sign into Clipious using token.
> 
> Works beautifully.

Fixed my issue, thanks for the step by step
