### ISSUE TITLE
Auto queue and autoplay any playlist video

### ISSUE THREAD

**Issue by WardPearce** [lamarios/clipious#348]
**Is your feature request related to a problem? Please describe.**
Greetings, currently when playing a video from a playlist (lets say video 52) it won't queue 53, 54, 55 etc next to be autoplayed. The only current way of doing this is skipping 51 videos.

**Describe the solution you'd like**
When in a playlist or the queue selection screen, when you select a video, that video will begin to play and all additional videos in the playlist after that will be queued.

**Comment by lamarios** [comment]
fixed in next release
