### ISSUE TITLE
HandshakeException while connected to Wi-Fi

### ISSUE THREAD

**Issue by Lavmint** [lamarios/clipious#354]
**Describe the bug**
When connected to the Wi-Fi I can get my list of subs only when spamming the refresh button for about 5-6 times. 
When I try to add video to a playlist is says: `HandshakeException: Handshake error in client (OS Error: TLSV1_ALERT_UNRECOGNIZED_NAME(tls_record.cc:592)) OK` so probably this is the error.

**To Reproduce**
Unfortunately I don't know how to reproduce the bug aside from my Wi-Fi. And I don't have access to other cable providers.

**Expected behavior**
There shall not be `HandshakeException` while connected to the Wi-Fi.

**Screenshots**
`HandshakeException` was provided by an alert window.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Degoogled LineageOS based on Android 13 with microG and Magisk
 - Version: 1.17.0 (latest f-droid)

**Additional context**
Provider PLDT, the Philippines. On the cell data (DITO) everything works ok.

**Comment by lamarios** [comment]
Can you try to enable the skip ssl verification toggle in the manage servers settings and see if it helps?

**Comment by Lavmint** [comment]
> Can you try to enable the skip ssl verification toggle in the manage servers settings and see if it helps? 

Sure, this did not help, got the same error

**Comment by lamarios** [comment]
owh I didn't see,  you're saying that everything works fine on a different connection (cell data) ? Then I'll close this as it's most likely a network issue on your end and not an issue with the app itself.

**Comment by Lavmint** [comment]
Logs just in case
[30-10_14-40-47.zip](https://github.com/lamarios/clipious/files/13201644/30-10_14-40-47.zip)

**Comment by lamarios** [comment]
thanks.  Do you have a VPN provider you could try on your wifi connection to see if works ?

**Comment by Lavmint** [comment]
> thanks. Do you have a VPN provider you could try on your wifi connection to see if works ?

Tried with Orbot (Tor VPN) with it enabled works fine

**Comment by lamarios** [comment]
Ok, I guess we know the culprit then :)
