### ISSUE TITLE
Integrated Updater

### ISSUE THREAD

**Issue by BuzzKnightbeer** [lamarios/clipious#355]
This would be great to not rely on F-Droid or something similar. Or at least having a notification that says there is an update available on GitHub.

I found this too: [ Android TV - Built in updater #302 ](https://github.com/lamarios/clipious/issues/302)

**Comment by jeremiah-k** [comment]
Check out Obtainium, it's a life saver
https://github.com/ImranR98/Obtainium

**Comment by lamarios** [comment]
I'll close those. Use accreacent on TV to manage updates of the app.
