### ISSUE TITLE
Not seeing bottom of the player in landscape

### ISSUE THREAD

**Issue by kozak243** [lamarios/clipious#356]
**Describe the bug**
When playing videos and turning phone into landscape mode, it doesn't show the bottom of player/video. Fullscreen button works just fine. (Also, turning into portrait doesn't exit the fullscreen player but that may be preferable, idk)

**To Reproduce**
1. Play a video
2. Turn phone landscape

**Expected behavior**
Fitting whole video in available space or/and covering whole screen

**Screenshots**
![image](https://github.com/lamarios/clipious/assets/115477155/2e56cfe7-893c-48e3-8fa3-03276eda3084)

**Smartphone (please complete the following information):**
 - Device: Oneplus Nord2 5G
 - OS: Android 13, DerpFest, degoogled & rooted with Magisk
 - Clipious Version: 1.17.0

**Comment by lamarios** [comment]
You need to switch to full screen first.

**Comment by kozak243** [comment]
But why I don't see bottom of the player in landscape mode? I don't have access to that button in that position.
I cannot enable full screen when the phone's on it's side so am I suppose to enable it before I put it in landscape? I use my phone almost only when in horizontal position with auto-rotation disabled so it is a pain to put in portrait mode just so I can access the fullscreen button.
It's so inconvenient I thought it was a bug 🤔

**Comment by lamarios** [comment]
I'll see what i can do for the next batch of fixes

**Comment by lamarios** [comment]
I'll leave this open as it is not fixed.
