### ISSUE TITLE
No thumbnails - Android Tv - Invidious self hosted

### ISSUE THREAD

**Issue by gianpo86** [lamarios/clipious#361]
As per title, clipious on android tv is not showing any video thumbnail. 

Fresh installation of invidious dated 31th October 2023: 2023.10.26-8087e64

Clipious latest on the 31th October 2023: 1.17.1

Thin client in invidious is disabled

Invidious is self hosted on docker (synology) and only reachable via LAN on dedicated port 

**Thumbnails are working if I select a public invidious server**

1. Open clipious

**Expected behavior**
Thumbnails are shown

**Android Tv (please complete the following information):**
 - Device: Philips Oled 806
 - OS: Android Tv 11
 - Version android Tv 4.19.182

**Comment by lamarios** [comment]
have you tried the stuff from the wiki about it ? https://github.com/lamarios/clipious/wiki/Common-Issues#video-thumbnails-not-working

**Comment by gianpo86** [comment]
Indeed I didn’t, thanks for the prompt reply and for pointing it out! I just googled a bit and that page did not show up, I will try and get back soon.

**Comment by gianpo86** [comment]
The port configured on invidious was still 443, but since I am running it internally the proper port was missing. Following the instructions in the Wiki made the trick! Thanks and thanks for the great app! Keep going!

**Comment by lamarios** [comment]
Great to hear this. Thanks !

**Comment by gianpo86** [comment]
Sorry for getting back here. If you want I can open a dedicated issue: same environment. Sadly the search history is keeping being empty also after several queries. Anything I missed again?

**Comment by lamarios** [comment]
Did you enable search history in the settings ?

**Comment by gianpo86** [comment]
:P just updated my comment: yes I did

**Comment by gianpo86** [comment]
Never mind, I open a dedicated issue with the details so it stays clean

**Comment by lamarios** [comment]
ok, i tested and indeed it is a bit borked. If you do an empty search the history will show which is not idea obviously... Can you open a new issue, so i'll fix it on the next round of fixes

**Comment by gianpo86** [comment]
YES I WILL! Thanks a lot for following the thread and have a great day
