### ISSUE TITLE
Remove this page

### ISSUE THREAD

**Issue by tvnmguy** [lamarios/clipious#363]
Remove this page👇🏻
![Screenshot_2023-11-02-14-19-57-893_com github lamarios clipious](https://github.com/lamarios/clipious/assets/116799295/8265e332-93f4-4e6d-89af-acf1e61032f2)

Before;
![Screenshot_2023-11-02-14-35-26-196_com github lamarios clipious](https://github.com/lamarios/clipious/assets/116799295/87c33655-15a7-42c3-9487-fe7f9d22764c)

After;
![IMG_20231102_143140_1](https://github.com/lamarios/clipious/assets/116799295/173b4d06-faa0-45bc-b553-8dbeb853571f)

**Comment by lamarios** [comment]
I have no idea what you mean by removing "this page". Can you describe what are you expecting ?

**Comment by lamarios** [comment]
You can play a video directly after loading it from a list: Settings > player > automatically play video on load

**Comment by lamarios** [comment]
OK. Got it. Its a bug somewhere. It's not supposed to do that, see my recording. Which version of the app are you using? It use to be a bug for a while that fixed in recent versions. 

https://github.com/lamarios/clipious/assets/1192563/11a9c15d-6907-4543-8cd9-2778c97704d3
