### ISSUE TITLE
Can't click to add/select a server on Android TV

### ISSUE THREAD

**Issue by jeremiah-k** [lamarios/clipious#364]
**Describe the bug**

**To Reproduce**
1. Install app via F-droid on Android TV running Android 8.1 
2. Open app
3. Can't click on anything.  I can't add my server or select a public one. This is the first android app I've tried that I've had this type of issue with.  I've tried with the remote and a mouse.

**Expected behavior**
I wanted to add my Invidious instance

**Screenshots**
![1000001547](https://github.com/lamarios/clipious/assets/17190268/0320e869-0dcb-4e1d-af7b-7157476f6b52)

**Smartphone (please complete the following information):**
 - Device: A95X Max
 - OS: Atvxperience ROM (Android 8.1 Oreo)
 - Version [e.g. 1.17.1]

**Additional context**
I can use the up and down arrows to select the different options / servers, but when I go to click or press "Enter" to select an option nothing happens.

**Comment by lamarios** [comment]
Actually a picture could be useful. Just to see if it's loading the proper ui.

**Comment by jeremiah-k** [comment]
> Actually a picture could be useful. Just to see if it's loading the proper ui.

Apologies.  I edited it with a screenshot.

**Comment by lamarios** [comment]
Hmm that's the proper ui but you're using mouse and keyboard on android TV? Do you have a remote to see if it works?

**Comment by jeremiah-k** [comment]
I tried with the remote first.   

First, using the arrow keys to jump between options, which does work to move up and down the menu options (Add new server, select a public server, down to "Start using Clipious" which doesn't work either, not a surprise because a server isn't selected), but when I click "Ok" it doesn't do anything.

On the remote I can press a button to enable the cursor, which sometimes is necessary in some Android apps when the arrow keys don't work to move between the selections.  That didn't work either, that's when I added a USB mouse to try.  None of the options worked.

**Comment by lamarios** [comment]
Strange. I'll need to check if there are any other key codes that can relate to "enter" or "OK"

**Comment by jeremiah-k** [comment]
I hadn't tried a keyboard yet, I just tried one now and somehow was able to add a server, using the arrow keys & pressing enter!  Thanks for that suggestion.

So I'm looking at my instances home screen and I still need to press enter on the keyboard to be able to select anything.  The "Ok" button on my remote doesn't work and neither does clicking with a mouse, but enter on the keyboard does work to select the option, so there does seem to still be an issue there somewhere.

One other thing, I'm unable to find an option to login in this UI.  I was able to on my phone which looks different.  Is it possible to login in this style UI?

Adding screenshots to show all of my options (and no login option).
![1000001551](https://github.com/lamarios/clipious/assets/17190268/86e222e0-c01b-48cb-9a15-fcc19eb0b61f)
![1000001552](https://github.com/lamarios/clipious/assets/17190268/8fe12008-79ef-4ef9-aaf3-b856f71cf1bd)
![1000001553](https://github.com/lamarios/clipious/assets/17190268/46457bac-5f67-4fea-a13a-21c6d71466e3)
![1000001554](https://github.com/lamarios/clipious/assets/17190268/eb263396-1a4b-4a0f-8ede-9dbdf481e3cf)
![1000001555](https://github.com/lamarios/clipious/assets/17190268/f7fc7574-4103-4595-a810-8fe4ec68171b)

**Comment by lamarios** [comment]
OK. Seems like the remote is sending a different key code then. For logging in it's in the same place as phone. Go to manage servers - > select your sever - > login.

**Comment by jeremiah-k** [comment]
I do see the login option now.  Thank you.

**Comment by jeremiah-k** [comment]
After searching a bit it seems like the keycode might be KEYCODE_DPAD_CENTER, since the OK button is in the center of a DPAD. I'll see if I can find out for sure tomorrow.

**Comment by lamarios** [comment]
Can try with the release below ? (not sure what's you box architecture, so i'll let you figure it out)

[app-arm64-v8a-release.zip](https://github.com/lamarios/clipious/files/13258753/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/lamarios/clipious/files/13258755/app-armeabi-v7a-release.zip)
[app-x86_64-release.zip](https://github.com/lamarios/clipious/files/13258757/app-x86_64-release.zip)

**Comment by jeremiah-k** [comment]
[app-armeabi-v7a-release.zip](https://github.com/lamarios/clipious/files/13258755/app-armeabi-v7a-release.zip) is the correct architecture for my box.  I just installed and unfortunately it's not working.

I also installed Key Mapper and recorded the key press for the OK button and can confirm it is DPad Center.

I have zero experience with flutter, but I ran this issues + your recent changes by GPT4 and these are the changes that it suggested.

```
const List<LogicalKeyboardKey> selectKeys = [
  LogicalKeyboardKey.accept,
  LogicalKeyboardKey.enter,
  LogicalKeyboardKey.numpadEnter,
  LogicalKeyboardKey.select,
  LogicalKeyboardKey.open,
  // Add DPAD_CENTER if it's not already handled by the existing keys
  LogicalKeyboardKey.dpadCenter,
];
```

**Comment by lamarios** [comment]
It doesn't exist there https://api.flutter.dev/flutter/services/LogicalKeyboardKey-class.html

**Comment by jeremiah-k** [comment]
Hmmm...  Indeed it does not.  Looking at the list, I'm trying to guess what else it could be.  Maybe `accept`, `execute`, `gameButtonStart` (unlikely, but maybe), `open`, or `select` ?

For now I was able to remap DPad Center to the Enter key using Key Mapper and it's working well so far.  There are warnings in the app that say the app could be killed, disabling the mappings. I've disabled the battery optimization features in the app settings so hopefully it will work in the long term.

Ideally I'd like to be able to run it without they Key Mapper, but it looks like this will work for now.

I really appreciate you taking time to try to help me and appreciate this project, as a whole.  Maybe this issue will be rare, only affecting a few older devices.  If you want help testing any other changes, I'd be happy to help with that. Otherwise feel free to close this issue.

**Comment by lamarios** [comment]
No worries, glad to help when the person asking the question is actually making effort, better than the many "it doesn't work" issues.

Can you try this one ? Added physical key mappings instead of just logical

[app-armeabi-v7a-release.zip](https://github.com/lamarios/clipious/files/13261889/app-armeabi-v7a-release.zip)

**Comment by jeremiah-k** [comment]
Yeah, I hear that.

I tried it and unfortunately it didn't work.  I looked at your changes and am seeing:
`const List<int> selectPhysicalKeys = [0x1100000017];`


Would `const List<int> selectPhysicalKeys = [0x00000017];` work .. maybe?
From: https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_DPAD_CENTER ?

**Comment by lamarios** [comment]
yeah, so what i did to come up with this number is to use the key event number (23) and use adb to send it to my emulator, the code then wa 0x1100000017, which didn't match with webpage. I'll add the other one and see

**Comment by lamarios** [comment]
[app-armeabi-v7a-release.zip](https://github.com/lamarios/clipious/files/13262443/app-armeabi-v7a-release.zip)

**Comment by jeremiah-k** [comment]
I installed it and there was no change

**Comment by mossmana** [comment]
You may also try adding a shortcut per https://docs.flutter.dev/ui/interactivity/actions-and-shortcuts.`@override
  Widget build(BuildContext context) {
    return Shortcuts(
      shortcuts: <LogicalKeySet, Intent> {
        LogicalKeySet(LogicalKeyboardKey.select): const ActivateIntent(),
      },
...`

If that works for you, I will investigate adding it as a built in activation via https://github.com/flutter/flutter/issues/1670, but that may require further discussion.

**Comment by lamarios** [comment]
I already have this in my code, see [here](https://github.com/lamarios/clipious/blob/28c54146ea23cdb5a74c9e4b00da989d92c8c8d2/lib/app/views/tv/screens/tv_home.dart#L62)
