### ISSUE TITLE
Add "customize app sections" and "video filters" to the TV UI

### ISSUE THREAD

**Issue by papa-legba** [lamarios/clipious#366]
**Is your feature request related to a problem? Please describe.**

I run a local invidious instance which I'm using to currate the YouTube channels my child has easy access to through setting up a local user and creating subscriptions.  Currently works great except said child could find new channels via the trending section. 

**Describe the solution you'd like**
Being able to filter certain channels as well as make it more challenging to find others (i.e. remove the trending section)  Would be amazing!

**Describe alternatives you've considered**
The features already appear and work well in the Android App but just aren't available in the TV UI settings. 

**Additional context**

**Comment by lamarios** [comment]
Valid concern, I'll add it to the things to do next.
