### ISSUE TITLE
add history support (ready)

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#38]
https://github.com/iv-org/invidious/pull/3654

**Comment by Outlet7493** [comment]
Doing this efficiently in it's current form could be difficult as the history API only returns a list of video IDs and not a list of video objects, meaning a request would be have to made for each video in the list.

**Comment by midasvo** [comment]
> Doing this efficiently in it's current form could be difficult as the history API only returns a list of video IDs and not a list of video objects, meaning a request would be have to made for each video in the list.

Could be cached?
