### ISSUE TITLE
Subscribed videos and history not showing

### ISSUE THREAD

**Issue by devnull69** [lamarios/clipious#380]
**Describe the bug**
I added an additional invidious instance to clipious and logged in to this instance. On the web ui of the instance I can clearly see my subscribed videos and my viewing history. But in Clipious those views are always empty (also after waiting for a few hours).

I tested the endpoint via
`https://<myinstance>/authorize_token?scopes=:feed`
and then
`https://<myinstance>/api/v1/auth/feed`
and all of the subscribed videos are showing just fine.

**Expected behavior**
Be able to view the subscribed videos on the subscriptions tab

**Comment by devnull69** [comment]
I tried using the COOKIE method instead of TOKEN method to login ... but it doesn't work either

**Comment by marcossmtp** [comment]
Same for me. In the suscription tab no videos. Hope to solve soon because it's really a necesary function.
