### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by senolfndk** [lamarios/clipious#382]
Can you add Turkish language?

**Comment by lamarios** [comment]
Someone has to contribute here:  https://hosted.weblate.org/projects/clipious/app-translation/

If you speak the language, please contribute.

**Comment by senolfndk** [comment]
> Birinin buraya katkıda bulunması gerekiyor: https://hosted.weblate.org/projects/clipious/app-translation/
> 
> Eğer dili konuşuyorsanız lütfen katkıda bulunun.
I'm not an expert on this subject
