### ISSUE TITLE
Changeable Double-Tap Seek

### ISSUE THREAD

**Issue by heare2code** [lamarios/clipious#386]
On original YouTube, you can change the double-tap seeking amount to 5, 10, 15, 20, 30, and 60 seconds. I always use the 5 second option and I enjoy YouTube more that way. Currently, Clipious does not bave such an option, and it's a huge let down for me when using this app as an alternative.

I think it would be great to implement the double-tap seek option because I and probably a lot of other people uses the feature frequently.

**Comment by lamarios** [comment]
will be on next release
