### ISSUE TITLE
Distraction Free Mode

### ISSUE THREAD

**Issue by matt873** [lamarios/clipious#387]
Can you separate comments from recommendations in distraction free mode? Comments are important in many cases as many creators share useful links there and also many people like to see comments under marketing or political videos. A separate toggle to enable/disable comments will be helpful. It would be even more helpful to have a separate toggle for enabling or disabling the queue function. Thanks.

**Comment by lamarios** [comment]
I don't think I will do this, first it kind of goes against the idea of distraction free and also I'm trying to keep the number of settings toggles low and I think there are already way too many.
