### ISSUE TITLE
Swiping down the video player goes to the video info page

### ISSUE THREAD

**Issue by demirdegerli** [lamarios/clipious#388]
I open a video:
![Screenshot_20231129-164117](https://github.com/lamarios/clipious/assets/67432156/f56fa63b-90d0-4da0-ac28-3ab3651a125f)
I swipe down or press the back button:
![Screenshot_20231129-164131](https://github.com/lamarios/clipious/assets/67432156/892d38aa-05d3-4edb-a270-21f25fbbb96e)
And this screen opens:
![Screenshot_20231129-164139](https://github.com/lamarios/clipious/assets/67432156/c6007d4f-6e37-413f-8baa-d56cb53d7a17)
When I expect it to open this page:
![Screenshot_20231129-164148](https://github.com/lamarios/clipious/assets/67432156/0310adae-0641-42cd-b0f0-9cb76542484a)

LibreTube, YouTube and NewPipe don't have this weird behavior. It goes back to the page that you clicked on the video. I know, it's not a bug but it drives me crazy. I'm sure all other users will appreciate this.

Also, swiping up doesn't work when I pull up the minimized video's title at the bottom. It only works when I pull up the video preview. (on the left of the minimized view)

**Comment by lamarios** [comment]
Looks like a big, Which version of the app are you using?

**Comment by demirdegerli** [comment]
Version: 1.17.3
Build: 40373

**Comment by lamarios** [comment]
OK. Seems like a bug. If you don't mind can you take a screen shot of all your settings? Last time this bug was there it was when specific settings were enabled.

No need to server settings.

**Comment by demirdegerli** [comment]
![Screenshot_20231129-182512](https://github.com/lamarios/clipious/assets/67432156/bd4b6e10-db39-4bdd-a7b2-07c6c6ed2908)
![Screenshot_20231129-182520](https://github.com/lamarios/clipious/assets/67432156/194af84b-ab87-46cd-a063-cafab83e5e16)
![Screenshot_20231129-182531](https://github.com/lamarios/clipious/assets/67432156/59e4e66f-7e5f-4ad9-b536-ac5af1eea12a)
![Screenshot_20231129-182536](https://github.com/lamarios/clipious/assets/67432156/dcdfb871-6ff8-41cd-a49b-b8399345e303)

**Comment by lamarios** [comment]
Awesome thanks. I'll have a look when I have some time.

**Comment by lamarios** [comment]
Found the problem it was because of the video auto play. Will be available in the next release.
