### ISSUE TITLE
"Audio only" mode works only when "proxy video" is not selected

### ISSUE THREAD

**Issue by marcogiorgio** [lamarios/clipious#392]
Hi,
I noticed that the "audio only" button works only if I don't select the option to proxy the streams from the invidious server. 
If I select the option, I get the infinite loading with the exclamation mark issue. Is this the intended behavior?
On my desktop PC I use Freetube and it works fine
Thanks

**To Reproduce**
1. Go to Settings -> Video Player -> Enable "Proxy videos"
2. Open a random video and switch to the "audio only" mode

**Expected behavior**
Only the audio of the video is played

**Screenshots**
![immagine](https://github.com/lamarios/clipious/assets/78936558/4961bea0-cbe9-4e46-aa30-f557753c8807)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14
 - Version: 1.17.3

**Comment by lamarios** [comment]
Not intended will have a look.
