### ISSUE TITLE
Subscribe To Channels With A Local Account

### ISSUE THREAD

**Issue by brucetheelephant** [lamarios/clipious#393]
**Is your feature request related to a problem? Please describe.**
Sometimes when instances go down (temporarily or permanently) you have to change between them. If you like certain channels, if you want quick access to them, if you want to follow their releases, if you want to have that information available in one space then you'll have to create an account on an instance, subscribe to said channels and watch your feed.

The problem is that when you change to a different instance you lose access to that account.

It's frustrating when I have to create multiple accounts on multiple instances and subscribe and resubscribe and resubscribe (and sometimes unsubscribe) to different channels again and again and again. It is difficult to keep them all in sync.

**Describe the solution you'd like**
I would like to be able to subscribe to channels without the need to make accounts and log in with those accounts to different instances and for that I would like to have one local account (similar to what you have in NewPipe).

**Describe alternatives you've considered**
I have not considered other solutions, I don't see any.

**Additional context**
None.

**Comment by lamarios** [comment]
This has been asked fews times already. I won't do local play lists / subscriptions. The app is meant to be an invidious client and it already has account with all those feature.

I know its now what you want but that's how I plan on keeping tlfor now. I might change my mind later but no promises.
