### ISSUE TITLE
Save Channel Playlists With A Local Account

### ISSUE THREAD

**Issue by brucetheelephant** [lamarios/clipious#394]
**Is your feature request related to a problem? Please describe.**
Sometimes channels create and publish many playlists which contain many pieces of content. It is difficult and time consuming to cherry-pick, to add each piece of said content, one by one to one's own playlist. It is exponentially more difficult, not to mention incredibly frustrating when you have to repeat all those actions if or when you have to switch instances because you lost access to your account because the instance went down (temporarily or permanently).

**Describe the solution you'd like**
I would like to be able to save entire (channel created) playlists to a local account.

**Describe alternatives you've considered**
I have not considered other solutions, I don't see any.

**Additional context**
None.

**Comment by lamarios** [comment]
This has been asked fews times already. I won't do local play lists / subscriptions. The app is meant to be an invidious client and it already has account with all those feature.

I know its now what you want but that's how I plan on keeping tlfor now. I might change my mind later but no promises.
