### ISSUE TITLE
Expand Pull Up Area of Playing-Now Bar

### ISSUE THREAD

**Issue by brucetheelephant** [lamarios/clipious#395]
**Is your feature request related to a problem? Please describe.**
When you want to play certain content, you press on it, it loads, you press play and said content plays. Sometimes you want to perform different actions while said content keeps playing. You do this by pressing and holding on it's "GIANT" thumbnail (which streches the whole width of the display) and pulling down and it pulls down to a playing-now bar. If or when you want to pull it back up you can't press and hold and pull up on the whole width of the bar, you have to press and hold and pull up only on it's "MINI" thumbnail (which is in the lower left corner). It's frustrating and it doesn't make sense.

**Describe the solution you'd like**
I would like to be able to press and hold and pull up the playing-now bar by pressing and holding and pulling up from anywhere on the bar. I think it can be done, I've seen it done in Phonograph Plus.

Describe alternatives you've considered
I have not considered other solutions, I don't see any.

Additional context
None.

**Comment by lamarios** [comment]
It used to be the case actually but i didn't like the experience to tap the other buttons (play, pause, close etc...) because a slight miss-tap where the finger drags a little bit would trigger the  drag gesture instead of. 

I'll leave this open as a reminder to look into it again in the future.
