### ISSUE TITLE
Live chat support

### ISSUE THREAD

**Issue by Tarlafic** [lamarios/clipious#401]
Show youtube live chat comments in live and live archive videos.

**Comment by lamarios** [comment]
Is that something invidious supports ?

**Comment by lamarios** [comment]
I see. If that's the case that's not something I would do. For few reasons:
- using Google apis can bring costs that I'm not willing to bare.
- it goes against the privacy respect that people using this app are looking for
- it's not available in invidious and this app is just an invidious client.


Ill closet this as its not something I'll be working on. Thanks :)
