### ISSUE TITLE
Disabling auto-rotate doesn't stop video from auto-rotating

### ISSUE THREAD

**Issue by WardPearce** [lamarios/clipious#407]
When auto-rotate is disabled on your phone. Tilting your phone sidewise slightly will still rotate the video.

**Comment by lamarios** [comment]
Do you use the lock full screen orientation setting?

**Comment by WardPearce** [comment]
yes

**Comment by lamarios** [comment]
Hmm yeha the last change I made to make the video full screen when the phone is rotated. I didn't know it would bypass the phone auto rotate  settings. I'll try to fix that for next release
