### ISSUE TITLE
Videos are no loading

### ISSUE THREAD

**Issue by edersong** [lamarios/clipious#41]
Installed Clipious and set my own server, authorized my user, app is loading all videos information but cannot open any video and thumbs are not loading also.
I'm using a Google Pixel 6 with Android 13.
See the printscreen below:

![Screenshot_20230307-144636.png](https://user-images.githubusercontent.com/64137913/223442422-5fb7edbf-a5c6-41d5-b6e8-f90cdb00edfa.png)

**Comment by simonSlamka** [comment]
Also have this issue and #5 is not the cause for me. My config does contain the FQDN. Any other possible causes? Thanks

**Comment by simonSlamka** [comment]
@edersong why close? now I need to open another issue ...

**Comment by edersong** [comment]
Sorry, reopened it ;-)

**Comment by simonSlamka** [comment]
> Sorry, reopened it ;-)

thanks :)

**Comment by lamarios** [comment]
You can use an up for the domain: config. See #47

**Comment by simonSlamka** [comment]
just got this fixed now by including the FQDN and ext. port in the docker-compose.yml file. apparently, it wasn’t enough to set the two in the config file (if it even reads it when using docker-compose).
