### ISSUE TITLE
feature req. when pressing a button or gesture (#31) to create a panel at the bottom or top

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#42]
when pressing a button (top left) or gesture (#31) to create a panel at the bottom or top

![IMG_20230307_180317.jpg](https://user-images.githubusercontent.com/113500363/223462247-af566243-51be-4ba6-86a6-b7e2e1777f8e.jpg)

https://user-images.githubusercontent.com/113500363/223462683-e15d88c4-dada-4458-8d46-a634bf300c1e.mp4

https://user-images.githubusercontent.com/113500363/223464663-a191a448-17fa-425f-aeba-e41b910eab82.mp4

in this panel will be the name of the video, the channel, and on the left of the names will be a thumbnail of the video. On the right side you can enter the video queue, and on the right side the video queue can close it (panel)

Also, it will be possible to close with a downward gesture. 
https://user-images.githubusercontent.com/113500363/223466440-1fa06fab-8156-4859-abb2-ed8d13f7fbdf.mp4

**Comment by lamarios** [comment]
Did it in my own way, not sure how far I'm going to implement this but it is usable for now. I'll close this issue. 

https://user-images.githubusercontent.com/1192563/224462564-a2844fae-0a03-4e0f-a460-81a13bb6e916.mp4
