### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [lamarios/clipious#421]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5772678905#L915

looks like you did not build the app with the same tooling

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/bfdc0f5fdf3bcdff95684065b155d574d6752884

**Comment by lamarios** [comment]
Hmm yeah. Not impossible. I had to redo the same tag multiple times because of Ci CD issues so maybe it caused issues with fdroid. Hopefully the next release will be OK.

**Comment by lamarios** [comment]
Fixed with last version.

**Comment by licaon-kter** [comment]
Can you reopen?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6908851724

I tried to add `flutter gen-l10n` in `build:` before `flutter pub run flutter_native_splash:create` but did not help

**Comment by lamarios** [comment]
yeah, i did a flutter upgrade and it fails in ci cd. I'll wait for it to be fixed on flutter side to try again as i already merged my code.
