### ISSUE TITLE
Please move the play button to somewhere i can reach in landscape mode

### ISSUE THREAD

**Issue by Lihewin** [lamarios/clipious#424]
In the video detail page, the play button is located at the centre of the album and the picture is **fixed** at the top of the screen, so when the phone is in landscape mode the screen only displays upper part of the picture and the play button is hidden below, i have to rotate my phone to play the video every time.Please try to design the button more reasonably, thank you for the work.👍
![Screenshot_20231220-004915_Clipious~2](https://github.com/lamarios/clipious/assets/62163831/90acbe08-13e4-4f8d-a6db-1b89a553900c)
![Screenshot_20231220-004921_Clipious](https://github.com/lamarios/clipious/assets/62163831/94f73a97-802b-453a-8651-4ea1d3326110)

**Comment by lamarios** [comment]
This layout will be in next release. Not going to lie this is minimal effort and not planning to do much more. Landscape on phone is really impractical and hard to build proper ui for.

![image](https://github.com/lamarios/clipious/assets/1192563/80820242-72de-42b4-aaa9-f5dac0005e22)
