### ISSUE TITLE
feature req. improve the video queue

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#43]
![338646.jpg](https://user-images.githubusercontent.com/113500363/223467726-92ea5055-3a2b-46b6-b694-d2ce71df982c.jpg)

https://user-images.githubusercontent.com/113500363/223470467-64f9a4b6-3b23-45a0-9b9a-385731bc407e.mp4

playlist button, when pressed, adds all songs from the video queue to the selected playlist

**Comment by lamarios** [comment]
Done
