### ISSUE TITLE
Playlists tab in spanish has the text not align

### ISSUE THREAD

**Issue by marcossmtp** [lamarios/clipious#431]
![IMG_20231222_210202.jpg](https://github.com/lamarios/clipious/assets/125501773/91483322-0569-41a9-b275-1502fecedbd7)

I can say it fails in a xiaomi redmi 9c with android 11 and in a samsung a33 with android 14. It seems a problem with the language text alignnament.
Same in the play menu:
![IMG_20231223_123035.jpg](https://github.com/lamarios/clipious/assets/125501773/1584a066-06af-4517-92b6-008a6fde6681)

**Comment by lamarios** [comment]
I had a quick look and it seems that flutter doesn't provide any way to set up text alignment on the bottom navigation bar :( I'll close this issue first. I'll update if i ever find a way.
