### ISSUE TITLE
SponsorBlock settings are not saved between sessions

### ISSUE THREAD

**Issue by GitHubington** [lamarios/clipious#435]
**Describe the bug**

SponsorBlock settings are not saved between sessions

**To Reproduce**

Load Clipious

Press
- Gear Icon
- Video Player
- SponsorBlock

Set options
- - Sponsor
- - Unpaid/Self Promotion
- - Endcards/Credits

Keep pressing the Back Button until you have exited Clipious

Load Clipious again

Press
- Gear Icon
- Video Player
- SponsorBlock

Note that that all options, Sponsor, Unpaid/Self Promotion, SponsorBlock, have all been reset.
Note also that even when you go back and set those options, SponsorBlock does not engage on videos that have skippable parts.

**Expected behavior**

All options, Sponsor, Unpaid/Self Promotion, SponsorBlock, should remain set.
SponsorBlock should engage on videos that have skippable parts.

**Smartphone (please complete the following information):**

 - Device: Xiaomi Mi A2
 - OS: Android 11 (PixelExtended 20211130)
 - Version Clipious 1.17.5

**Comment by lamarios** [comment]
thanks for catching this. will be released in next version
