### ISSUE TITLE
Nothing is playing on Android tv

### ISSUE THREAD

**Issue by allmightyasian** [lamarios/clipious#442]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 7a]
 - OS: [e.g. Android 13]
 - Version [e.g. 1.14.1]

**Additional context**

**Comment by lamarios** [comment]
It works for me.

(low effort bug report, low effort resolution)

**Comment by allmightyasian** [comment]
> It works for me.
> 
> (low effort bug report, low effort resolution)

Good for you
