### ISSUE TITLE
black screen on play

### ISSUE THREAD

**Issue by euDominic** [lamarios/clipious#447]
**Describe the bug**

With today's update, no more content is played.
With version 1.17.7 I only get a black image with my invidious instance. Even with remote servers.
yesterday everything still worked with the old version. use it on a nvidia shild with android tv 11

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nvidia shield version 2019
 - OS: Android TV
 - Version 11

**Additional context**
From my iPhone and the yattee app, I can access my invidious instance and play content without any problems.

downgrade to version 1.17.6, and all works again.

**Comment by lamarios** [comment]
Big miss on my end, will release the fix soon

**Comment by lamarios** [comment]
available in 1.17.8
