### ISSUE TITLE
Non-FOSS in F-Droid build - objectbox

### ISSUE THREAD

**Issue by licaon-kter** [lamarios/clipious#459]
https://github.com/lamarios/clipious/commit/b57ec181f6950485d0866303d558b3947765ad59#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25R43

all the versions are affected :(

ref: https://objectbox.io/faq/#license-pricing

/LE: ref: https://gitlab.com/fdroid/fdroiddata/-/issues/3170#note_1727218578

**Comment by licaon-kter** [comment]
disabled all: https://gitlab.com/fdroid/fdroiddata/-/commit/77549245c76f3430bf21a8086efe1fe8d7aaf80a

Note that since it's a DB think, you might need to change the actual DB and maybe release a version that has both DBs so it can migrate from old to new.

We'll test when that's ready.

**Comment by licaon-kter** [comment]
Some alternatives listed in the last:
* Realm
* Room
* LitePal
* SQLDroid + KTorm
* SQLDelight.

**Comment by lamarios** [comment]
Question though, how are the f-droid users supposed to migrate if they can't update through f-droid if it is getting removed ?

Before i start any change. I'm thinking to use Hive. License looks ok. please confirm.

**Comment by licaon-kter** [comment]
> I'm thinking to use Hive. License looks ok. please confirm.

links?

**Comment by lamarios** [comment]
Alright thats good to know. Thank you.

Sorry. Forgot the link: https://pub.dev/packages/hive

**Comment by lamarios** [comment]
Will go with isar actually as the author is the same as hive and suggests people to use isar instead.

**Comment by licaon-kter** [comment]
@lamarios note that Isar needs to be built in the F-Droid recipe, eg: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/miru.miaomint.yml#L463-L471

**Comment by lamarios** [comment]
I realised way too late that I won't be able to use isar... It doesn't work on android TV emulator and the devs don't seem interested in fixing it.

Still looking for good alternatives.

**Comment by Outlet7493** [comment]
I found [floor](https://pub.dev/packages/floor) which maybe you already came across but is inspired by Room (SQLite). (Apache 2.0)

It seems to support TV emulator from what I can see.

**Comment by lamarios** [comment]
Yeah I checked it. Didn't really like the api. Might go with sembast or something like this. Simpler in the concept.

**Comment by lamarios** [comment]
After much head banging against the walls. I'll go the nuclear options. There will be no migration and app will be reset on next version first launch. 

Sorry for the inconvenience. Fortunately the data the app keeps is not crucial. (no locals subs, playlists etc...)

**Comment by lamarios** [comment]
The version without object box has been released. What do i need to do to put the application back on f-droid ?

**Comment by licaon-kter** [comment]
Will take a look, build, then add to the recipe. :)

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/eb78483e82fdca1ee56a38487f89c9fd6bbac1a5
