### ISSUE TITLE
Option to remove the trending and popular tab

### ISSUE THREAD

**Issue by GET100PERCENT** [lamarios/clipious#46]
It will be helpful if a option (in settings) is given to remove the trending and popular tab.

**Comment by lamarios** [comment]
Is it actually really necessary ?  There's an option to select where you land when starting the application, other than having 2 extra tabs at the bottom you don't have to open those.

**Comment by GET100PERCENT** [comment]
No its not necessary, but if there is an option to remove them, it will be better as they are not usable to me.

**Comment by GET100PERCENT** [comment]
Just like some apps preinstalled on my phone which i never use.

**Comment by lamarios** [comment]
I don't think I'm going to do this one.

Extra tabs don't take resources unlike unwanted apps that can run in the background or take storage space.
