### ISSUE TITLE
Carry over title of video when sharing

### ISSUE THREAD

**Issue by thopanX** [lamarios/clipious#463]
**Is your feature request related to a problem? Please describe.**
When I share a video link to Mastodon (i.e. Tusky app) the video title is not carried over.

**Describe the solution you'd like**
Carry over title to app.

**Comment by lamarios** [comment]
I'm not sure I understand. When sharing a video it's just a link of the video itself, nothing else. So it can be handled by intent that are expecting links only.

**Comment by lamarios** [comment]
That is an issue with the app receiving the link then. If you share the link with what's app or signal, it will go and fetch the data from the link itself.

If I add any other text than just the link apps that just expect a url won't know how to handle it.
