### ISSUE TITLE
Support for android tablets 

### ISSUE THREAD

**Issue by farzana840** [lamarios/clipious#466]
The app fine works on tablets but the layout is very hard to use. Lots of padding . The actual interface is very small and at times it can be a bit irritating. The mini player needs some fixing too. A little ui adjusting should do the trick
![Screenshot_20240126_064006](https://github.com/lamarios/clipious/assets/68196826/29e18a2c-5604-4c67-b27f-144939a17e00)
![Screenshot_20240126_064212](https://github.com/lamarios/clipious/assets/68196826/f642782a-4815-4560-9c9d-378c889d75f8)
You can take inspiration from the youtube interface. Everything fits nice and smooth. Rest all good. Really appreciate your work 
![Screenshot_20240126_064557_YouTube](https://github.com/lamarios/clipious/assets/68196826/400b1bef-9668-4d20-8040-0a2fd84a614a)

**Comment by lamarios** [comment]
I've been planning to work on this, it's probably next on my list after I migrate the dB libraries to be back on f droid.

**Comment by farzana840** [comment]
> I've been planning to work on this, it's probably next on my list after I migrate the dB libraries to be back on f droid.

Eagerly waiting!

**Comment by lamarios** [comment]
Started to look into it, here's an early look:
Home screen:
![image](https://github.com/lamarios/clipious/assets/1192563/e517e27c-aaf0-4e96-b5c1-2731586193fc)

Video Screen:
![image](https://github.com/lamarios/clipious/assets/1192563/85f69c9a-e1d0-41c5-8acb-18fb0428fb9d)

Channel Screen:
![image](https://github.com/lamarios/clipious/assets/1192563/1e202ecc-2a36-42a4-86ab-277ec72e4967)

I haven't done the player yet, but it should be something very similar to the video screen

**Comment by lamarios** [comment]
Some progress, got the video player working properly:

[Screencast from 2024-02-12 14-38-31.webm](https://github.com/lamarios/clipious/assets/1192563/68a475ef-412d-471f-a0d6-5ed48b1be228)

I'm still not super happy about how the mini player looks on tablet, too much spacing. I'll try to figure out something, it's hard to make drastic changes for tablet without breaking the phone on this part.

**Comment by lamarios** [comment]
available in version 1.19.0
