### ISSUE TITLE
When return youtube dislikes fails, the whole video will fail to load

### ISSUE THREAD

**Issue by WreckingBANG** [lamarios/clipious#468]
**Describe the bug**
When i click on any Video on any Server i get the Error Message: Could not Load Video

**To Reproduce**
1. Click on any Video
2. See error

**Expected behavior**
The Video should Load

**Screenshots**
![Screenshot_20240129-160816](https://github.com/lamarios/clipious/assets/86848811/733da717-ed53-4762-beb9-8764dc4b2fdd)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: GrapheneOS 14 (UQ1A.240105.004)
 - Version: 1.17.9

[INFO] [Service] - 2024-01-29 16:07:10.161 - Response from GET https://xxxxxxxxxx/votes?videoId=nKu_3kp_EIY, status: 502 

[INFO] [Video post process] - 2024-01-29 16:07:10.001 - Filter + DeArrow took 0ms for 20 videos

**Comment by WreckingBANG** [comment]
Oh, sorry and thank you. Now it works again.

**Comment by lamarios** [comment]
No worries. I'll reopen this as there should be a fix so that loading a video doesn't fail if third party stuff fails.
