### ISSUE TITLE
Video/Thumbnails are not loading

### ISSUE THREAD

**Issue by 8mpty** [lamarios/clipious#47]
Simply, videos and thumbnails are not loading when using my own "Private Instance".

 This issue is quite similar to https://github.com/lamarios/clipious/issues/41# and a possible solution was provided in https://github.com/lamarios/clipious/issues/5# but it still would not load.

My invidious setup uses Portainer and to access to my own instance is by using the IP address with its respective Port that is assigned ex. http://192.168.1.69:4476. I am not able to set it up with domains like in https://github.com/lamarios/clipious/issues/5# as my ISP does not allow port forwarding so I won't be able to access it publicly but that is not a problem. 

I was just wondering if there are any other users with my use case and have no problems/solved it?

**Comment by 8mpty** [comment]
LOL nevermind fixed it.

**Comment by xrfmkrh** [comment]
Same prob. I only use my local instance. How did you solve this?

**Comment by 8mpty** [comment]
Yo, sorry for the late reply but you would have to edit your config.yml
file of your invidious instance but if you are using portainer stacks or
docker compose, it is way easier as you just need to edit the compose file.
There will be a part in that config file where it says
# external_port:
# domain:

remove the "#" and add in your port assigned to that invidious instance and
the domain is the ip address of that server/instance.
ex.
external_port: 6969
domain:192.168.1.69

This works on my end but should work with yours as well,

**Comment by teemue** [comment]
I spent two hours solving this problem..
domain, ssl + nginx + dockerized invidious

Turns out external port had to be 443. Hence:
        domain: <fqdn> 
        external_port: 443
        https_only: true
