### ISSUE TITLE
Missing hash key: "commentRenderer"

### ISSUE THREAD

**Issue by UlyssesZh** [lamarios/clipious#472]
Sometimes the comment section cannot be loaded, and `Missing hash key: "commentRenderer"` is shown instead. Not steadily reproduced. The video in the screenshot is HEVkXONbQx4.

![Screenshot_20240202-191257](https://github.com/lamarios/clipious/assets/26196187/cc9949b1-d673-46ea-b465-575d7484228b)

 - Device: Samsung Galaxy S20
 - OS: Android 11, One UI 3.1
 - Clipious version: 1.17.8
 - Invidious version: 2024.01.29-c005ada

**Comment by lamarios** [comment]
I'm guessing server issue here. When comments can't be loaded the error message from the server will be displayed.

I tried that same video on my server and comments are showing properly.

![Screenshot_20240203-142000](https://github.com/lamarios/clipious/assets/1192563/9cc0adf3-c52a-4849-859e-eafbae16d555)

**Comment by UlyssesZh** [comment]
So the error message is the message sent from the server as is? That makes sense because the string `commentRenderer` never appeared in Clipious's code but only appeared in Invidious's code. I cannot see related error messages in the logs of Invidious, though.

**Comment by lamarios** [comment]
Yes. It should be the error from the server.

**Comment by UlyssesZh** [comment]
I updated the server, and I haven't seen this error for a while. I think it should be safe to close this issue. Sorry for bothering!

**Comment by lamarios** [comment]
No worries :)
