### ISSUE TITLE
clipious removed from F-Droid?

### ISSUE THREAD

**Issue by haruzept** [lamarios/clipious#474]
Hello,

i can't find clipious on F-Froid App and also not on the webpage (https://f-droid.org/packages/com.github.lamarios.clipious/).
Is the project removed from F-Droid or is it a bug/mistake by F-Droid?

Thanks

**Comment by lamarios** [comment]
It's coming back. See https://github.com/lamarios/clipious/issues/459

**Comment by IzzySoft** [comment]
Speaking of which: [you've asked me](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12912#note_1363366963) to remove Clipious from IzzyOnDroid a year ago, but the IzzyOnDroid badge is still shown in your Readme – now linking to a 404 page. Do you want Clipious restored at IzzyOnDroid, or did you just forget to remove the badge, @lamarios?

**Comment by lamarios** [comment]
My mistake sorry. I'll remove it from the read me

**Comment by IzzySoft** [comment]
No prob, thanks – I'd also have restored the app if that was the intention. Just that 404 is a little irritating :wink:
