### ISSUE TITLE
Support Unified Push

### ISSUE THREAD

**Issue by seang96** [lamarios/clipious#475]
**Is your feature request related to a problem? Please describe.**
Unified Push is a protocol to send the push notification through one background process across supported applications which reduces background connections and improves battery life.

**Describe the solution you'd like**
Add support for unified push. Documentation is accessible here https://unifiedpush.org/

**Describe alternatives you've considered**
No other options are FOSS or require the background service that is currently implemented.

**Additional context**
There are open source projects using this already such as matrix clients that may be good references for how it works.

**Comment by lamarios** [comment]
The app doesn't have push notifications. I'm not sue in what way this will help.

**Comment by seang96** [comment]
I see notifications as a beta option in 1.18.0's settings.

**Comment by lamarios** [comment]
Correct. All is done locally so it's not really a push notification. A "task" handled by android work manager is spawned at regular interval to check if there are new videos and will trigger a notification if it is the case.

I'll close this ticket.
