### ISSUE TITLE
[App Feedback] Minor: Depending on how the sentence is supposed to read, either the 'u' should be capitalized or the question mark should be removed

### ISSUE THREAD

**Issue by dewittlebook** [lamarios/clipious#485]
**Runtime info:**
[Device] Manufacturer: Google / Brand: google / Model: Pixel 6a / Hardware: bluejay
[Android] Version: 14.11224170 (REL)
[Clipious] Version: 1.19.0 Build: 4045

**Feedback:**
Depending on how the sentence is supposed to read, either the 'u' should be capitalized or the question mark should be removed

**Screenshot:**
![app screenshot](https://i.imgur.com/ik9clCp.png)

**Comment by dewittlebook** [comment]
This is not a major issue

**Comment by Outlet7493** [comment]
Fixed in https://github.com/lamarios/clipious/pull/492 but for future reference, strings can be edited in:
- https://github.com/lamarios/clipious/blob/master/lib/l10n/app_en.arb
- https://hosted.weblate.org/projects/clipious/app-translation/
