### ISSUE TITLE
Include 'Add to Playlist' option for currently playing video (when using Tablet)

### ISSUE THREAD

**Issue by cameronj86** [lamarios/clipious#487]
**Is your feature request related to a problem? Please describe.**
There are videos that I realize I won't finish in one sitting, want to watch on my tablet/phone instead of my phone/tablet, or I want to save the video and rewatch it later. Currently the 'add to playlist' option doesn't appear for the currently playing video.

**Describe the solution you'd like**
Add to playlist option can be on the same line as the `Video/Audio Only` toggle, or next to the `Subscribe` button. One alternative position is for it to be an option within the `Share` options if you don't want to add it to the existing UI.

**Describe alternatives you've considered**
My current  workaround is to go back to the search results within clipious, and click the three dots to add it to a playlist. Not ideal, but especially cumbersome when I am using a direct link instead of a video that I searched for. In those instances, I have to start a new search for the video I'm _currently_ watching in order to add it to a playlist.

**Comment by lamarios** [comment]
Good suggestion, meanwhile the most convenient way might be to go to the history tab.

**Comment by cameronj86** [comment]
> Good suggestion, meanwhile the most convenient way might be to go to the history tab if you're using an account on your invidious instance.

Just played around w/ it on my phone & tablet after your post and realized a discrepancy. The `Add To Playlist` is present on the main mobile layout but it's missing in the (otherwise very snazzy and great) new tablet layout.
