### ISSUE TITLE
Selecting a section as default is broken

### ISSUE THREAD

**Issue by kubo6472** [lamarios/clipious#489]
Note: This is zero priority, I can absolutely live with this issue being present.

**Describe the bug**
When you select a section as default (house icon) and then remove sections, it jumps to the next one.

**To Reproduce**
1. Edit sections
2. Set one as default
3. Remove one above
4. See it jumping

**Expected behavior**
Doesn't make sense this way, since you can remove all sections anyway. Selecting one as default should 100% remember which one was selected and keep it that way. It tries to does this, as seen on the screen recording, but not always.

**Screenshots**
https://i.imgur.com/MTsP2XX.mp4

**Smartphone:**
 - Device: Pixel 6a
 - OS: Android 14
 - Version: 1.19.0

**Comment by lamarios** [comment]
Probably a UX issue but then I see very small use case for people to remove all sections. (thought it was requested once, hence the possibility to do so)
