### ISSUE TITLE
No UTF-8 encoding in channel description

### ISSUE THREAD

**Issue by kubo6472** [lamarios/clipious#491]
Note: This is zero priority, I can absolutely live with this issue being present.

**Describe the bug**
See the screenshot, random charaters from non-utf-8 letters.

**To Reproduce**
1. Check specific channel's description

**Expected behavior**
Readable text

**Screenshots**
![Screenshot_20240226-152815_Clipious](https://github.com/lamarios/clipious/assets/26146502/79f1d157-0899-4f70-b7d3-ef35d263202c)

**Smartphone:**
 - Device: Pixel 6a
 - OS: Android 14
 - Version: 1.19.0

**Comment by Outlet7493** [comment]
Can you share the channel ID/url please? I can't reproduce this on some other channels (with cyrillic or others).

**Comment by Outlet7493** [comment]
For reference: https://redirect.invidious.io/channel/UCD5iDdhsh6fta5piIv6lFCA

I still can't reproduce this:
![utf8](https://github.com/lamarios/clipious/assets/122801553/ca88dd31-e387-478d-b699-a2dc7c5bdd51)

Tested on:
- Pixel 7 & 7a
- OS: Calyx & Graphene 14
- Clipious: 1.19.0 (4045)

**Comment by lamarios** [comment]
see this issue: https://github.com/lamarios/clipious/issues/408

most likely an instance issue

**Comment by lamarios** [comment]
Yes, if the issue is not happening on all servers then it is a server issue. Unfortunately I don't know what is the issue and how to fix it, that is a question for invidious.
