### ISSUE TITLE
Suggest changing to a better video player

### ISSUE THREAD

**Issue by Pantyhose-X** [lamarios/clipious#493]
**Is your feature request related to a problem? Please describe.**
Suggest changing to a better video player [ArtPlayer](https://artplayer.org/document/en/) 

**Describe the solution you'd like**

Demo  https://artplayer.org/  Modify 132 lines of code
```
        url: 'https://raw.githubusercontent.com/Pantyhose-X/Pantyhose-X/main/subtitle.srt',
```
You can put hundreds of languages in a .srt file, you just need to select the languages you want to display at the same time.
and One video display multiple subtitle files at the same time.
It supports font color selection for each language.
![555555555555554](https://github.com/TeamNewPipe/NewPipe/assets/42504385/ee3026c3-7bf0-4e52-883c-735308e88da2)

**Additional context**
https://github.com/zhw2590582/ArtPlayer
https://artplayer.org/document/en/

**Comment by lamarios** [comment]
Clipious is not using javascript.
