### ISSUE TITLE
would like a new feauture 

### ISSUE THREAD

**Issue by Acid4t** [lamarios/clipious#499]
**Is your feature request related to a problem? Please describe.**
idk,i didn't go through all but i think it's not

**Describe the solution you'd like**
like a snaptube like function.i want to download stuff straight to the phone's storage

**Describe alternatives you've considered**
i love this app..no more feautures i could dream of

**Additional context**
like in snaptube you can download straight to the storage..i just wanna download some songs

**Comment by TheRouce** [comment]
This is an existing feature. Press and hold on the thumbnail of a video until the context menu appears then click download

**Comment by lamarios** [comment]
latest version allows to copy a downloaded video to the phone's download folder
