### ISSUE TITLE
Fit videos to the screen

### ISSUE THREAD

**Issue by GET100PERCENT** [lamarios/clipious#51]
It would be nice if all videos (even low resolution videos) will play occuping the whole size of the display. 
 In other words all videos should be fitted to the screen size while playing.

**Comment by Kreuger** [comment]
Are you talking about how the video doesnt change to landscape mode in fullscreen unless you have screen rotation enabled on your phone? Because I agree, it should either be an option or do it automatically.

**Comment by GET100PERCENT** [comment]
> Are you talking about how the video doesnt change to landscape mode in fullscreen unless you have screen rotation enabled on your phone? Because I agree, it should either be an option or do it automatically.

No, i mean low resolution videos doesn't occupy the whole screen size in landscape mode, they become in their original size/resolution (less than the screen size),which i don't want.
In vlc if you play a video of 144p , it will be played in the whole screen size rather being a small video at the centre .

**Comment by Kreuger** [comment]
I imagine that would be because stretching it to fill the screen ruins the quality.

**Comment by GET100PERCENT** [comment]
> I imagine that would be because stretching it to fill the screen ruins the quality.

You are right, but watching such small videos will incresae the eye strain.

**Comment by lamarios** [comment]
Do you have a video to share? In theory the video should occupy the space available. Might be black birders encoded directly in the video itself.

**Comment by GET100PERCENT** [comment]
https://invidious.privacydev.net/watch?v=tgtZr1WHj9Y
![Screenshot_20230319-134517](https://user-images.githubusercontent.com/116144024/226162489-915a995f-6a66-41dc-889d-6e87df36772f.jpg)
![Screenshot_20230319-134429](https://user-images.githubusercontent.com/116144024/226162490-95394df2-8beb-4dfa-adb5-0a671404abf6.jpg)
https://www.youtube.com/watch?v=tgtZr1WHj9Y

**Comment by GET100PERCENT** [comment]
> https://invidious.privacydev.net/watch?v=tgtZr1WHj9Y ![Screenshot_20230319-134517](https://user-images.githubusercontent.com/116144024/226162489-915a995f-6a66-41dc-889d-6e87df36772f.jpg) ![Screenshot_20230319-134429](https://user-images.githubusercontent.com/116144024/226162490-95394df2-8beb-4dfa-adb5-0a671404abf6.jpg) https://www.youtube.com/watch?v=tgtZr1WHj9Y

Here the second screenshot is playing the video in 144p.

**Comment by lamarios** [comment]
ok, i can see the problem. I'll look into it in my next round of fixes.

**Comment by lamarios** [comment]
in version 1.11.0
