### ISSUE TITLE
No bottom navigation bar

### ISSUE THREAD

**Issue by judemont** [lamarios/clipious#512]
**Describe the bug**
The bottom navigation menu does not appear on the home page.

**Screenshots**
![Screenshot_2024-03-28-12-14-33-561_com.github.lamarios.clipious.jpg](https://github.com/lamarios/clipious/assets/96385330/47ddf41e-5243-44ae-bf39-3a0e3d2c8809)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 10
 - OS: Miui 14.0.8 (Android 13)
 - Version [e.g. 1.19.1]

**Comment by lamarios** [comment]
If you're not logged in then you're seeing what you're supposed to. Subscription, playlists and history are features linked to an invidious account.

**Comment by lamarios** [comment]
No worries :)
