### ISSUE TITLE
The video returned by YouTube isn't the requested one. (Android client)

### ISSUE THREAD

**Issue by marcogiorgio** [lamarios/clipious#514]
Hi,
When I click on a video to reproduce it, I get the error:

`The video returned by YouTube isn't the requested one. (Android client)`

This started a couple of days ago. I don't know why..

**Smartphone:**
 - Device: Pixel 6
 - OS:  Android 14
 - Version 1.19.2

**Comment by lamarios** [comment]
It's an issue with invidious.

https://github.com/iv-org/invidious/issues/4498

**Comment by marcogiorgio** [comment]
> It's an issue with invidious.
> 
> [iv-org/invidious#4498](https://github.com/iv-org/invidious/issues/4498)

Ty! I'll follow the issue in the Invidious repo

**Comment by ThaDaVos** [comment]
Seems there's a fix out for invidious, at least something is merged and a new docker image was pushed, but now instead of the app throwing an error, it just does not play

**Comment by ThaDaVos** [comment]
Nevermind that, it works on my phone (Android 13, Asus ROG Phone 5s) but not on my tablet (Android 7, Shield Tablet K1)

**Comment by luckkmaxx** [comment]
Yeah, seems to be fixed in latest docker image.

**Comment by lamarios** [comment]
Seems to be fixed, i'll close this ticket.

**Comment by ThaDaVos** [comment]
@lamarios - before creating a new ticket, any idea why the same version of the app works on my phone and not on my tablet?

**Comment by lamarios** [comment]
Not sure why, That might be a question for invidious. The app didn't change, if it worked before invidious fix and not after it's an issue with invidious.

**Comment by ThaDaVos** [comment]
I figured it out, partially - DASH is non-functional and max-quality I can select is 720p - this wasn't the case before the update and only happens on my Tablet - the thing is, it works through the web interface.

Second thing, when I open a video, it won't auto-play, I have to set the quality for it to start playing now

**Comment by ThaDaVos** [comment]
Is there any logging/debug I can enable to see what source it picks and stuff?

**Comment by Alma101** [comment]
I'm also having this exact issue right now but I'm using mi box s 4k 2nd gen latest software with dash on and off

**Comment by cameronj86** [comment]
Latest version of invidious was released last night to tackle this issue.

If you are running `:latest` on docker, the go to the invidious folder and:

1. `docker compose down` to stop the container
2. `docker compose pull` to grab the version released yesterday
`docker compose up -d` Restart the container (detached)

**Comment by ThaDaVos** [comment]
> I figured it out, partially - DASH is non-functional and max-quality I can select is 720p - this wasn't the case before the update and only happens on my Tablet - the thing is, it works through the web interface.
> 
> Second thing, when I open a video, it won't auto-play, I have to set the quality for it to start playing now

Seems to worsen even - now 360P is the max I can select, but only on one of my devices - on my phone I can use DASH without issues
