### ISSUE TITLE
Local subscriptions (without subscribing to an instance)

### ISSUE THREAD

**Issue by pi99y** [lamarios/clipious#516]
From a privacy and ease of use standpoint I would (as an user) love an option to keep subscriptions locally on my device without the need to register with an instance.

This option could co-exist with current ~registered/online subscriptions in at least two-ways:
a) user chooses a SINGLE WAY TO KEEP subscriptions "locally OR online" in preferences 
OR
b) user has the option to select ONE or BOTH WAYS TO KEEP "locally AND / OR online"

I like the terms "local subscriptions" vs "online subscriptions" since they are descriptive and don't introduce new terminology to "subscribing", but if for a reason further differentiation is desired, the local option could be called something like "local bookmarks".

If the current ~online subscriptions are a way of promoting instances (but I don't really see how that works) this could still be set as a default with users having an option to enable local subscriptions if they so desire and existing users not being bothered with the change.

Thanks for considering it.

**Comment by lamarios** [comment]
I'm not planning to do this. The app is an invidious client and will stick to what invidious offers. I believe libretube / new pipe offer what you want.

**Comment by pi99y** [comment]
OK, I respect that. I am aware of the two apps you mention however none of those two work with invidious.

**Comment by Retold3202** [comment]
@lamarios I hope that this will be reconsidered. 😕

Being able to subscribe to channels locally is a must-have feature IMO, every other FOSS YouTube client that I can think of supports it. You shouldn't be stuck at the whim of Invidious instances that could be down at any time, or even just go offline for good entirely. Why not have an instance agnostic approach? 

> The app is an invidious client and will stick to what invidious offers. 

This doesn't make sense to me. Why would Invidious need to implement this feature? Invidious instances are online and accessed through the web individually, an app like this is completely different.

And could you not also make this same argument for other features this app offers, such as SponsorBlock, DeArrow, & video downloads? 

Clipious is a great app that I genuinely want to be able to use, and I appreciate your time and work on it, but not having this feature is a deal-breaker for me and many others, so I hope you will reconsider your stance.

**Comment by lamarios** [comment]
Will be in version 1.20.0.

**Comment by pi99y** [comment]
@lamarios Thank you very much for reconsidering this and adding the feature! I'm a bit late to realize it was added, but I'm super happy and I believe it's for the better!
