### ISSUE TITLE
No thumbails if behind nginx http-auth

### ISSUE THREAD

**Issue by wieluk** [lamarios/clipious#518]
My thumbails work fine if i disable http-auth but with auth enabled and server changed in the app to user:pass@invidious.instance.com they won't load. 

Has anyone experienced this?

I have https_only: true , external_port: 443 and domain: invidious.instance.com in my config.

**Comment by gabriel-eladi** [comment]
what do you mean by `http_auth`? do you mean [HTTP basic auth](https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html)? if so, then i've also tried turning on HTTP basic auth for my instance, and setting the server to `https://user:password@invidious.instance.com` and I couldn't even watch videos, let alone see the thumbnails.
i'm not sure if HTTP basic auth is supported for Clipious.

**Comment by wieluk** [comment]
Yea i mean http basic auth.
On #54 the the login for http auth is fixed so it seems to work for some with auth.

**Comment by lamarios** [comment]
https://github.com/yattee/yattee/issues/731 yattee faced same issue. will try to look into it next

**Comment by lamarios** [comment]
Fix will be in next release
