### ISSUE TITLE
Swiping between tabs can cause scrolling to misbehave.

### ISSUE THREAD

**Issue by WardPearce** [lamarios/clipious#527]
**Describe the bug**
Sometimes swipping through tabs causes scrolling to go horizontal instead.

**To Reproduce**
https://files.catbox.moe/zmlnvz.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13
 - Version: 1.19.5

**Comment by lamarios** [comment]
I agree it can be a bit annoying. I'll see if I can disable that horizontal scrolling.

Funny enough. The issue happened to me and was surprises that no one raised issue yet on this. The 5 mins later I got the notification for this issue.

**Comment by WardPearce** [comment]
haha, maybe check your phone for backdoors 😉
