### ISSUE TITLE
Youtube block third party apps

### ISSUE THREAD

**Issue by Raffy-ID** [lamarios/clipious#528]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 7a]
 - OS: [e.g. Android 13]
 - Version [e.g. 1.14.1]

**Additional context**
https://www.google.com/url?q=https://www.theverge.com/2024/4/15/24131338/youtube-ad-blocker-crackdown-mobile-apps&sa=U&ved=2ahUKEwjNopGn0saFAxU5b2wGHb30CJAQxfQBegQIBhAC&usg=AOvVaw3rvA-3CaGVvHfJaOORxira

Recently Youtube tries to third party apps as of 2024 new policy, starting from April, all third party must comply with Youtube API. What's the state of clipious then?

**Comment by lamarios** [comment]
Clipious doesn't use Youtube API it uses invidious' which itself doesn't use Youtube API I believe so clipious should be safe from this but keep in mind that invidious is doing something that youtube doesn't like it will likely try to block it one way or another.
