### ISSUE TITLE
[App Feedback] I don't  understand, what is the hash key

### ISSUE THREAD

**Issue by Rx0g** [lamarios/clipious#529]
**Runtime info:**
[Device] Manufacturer: HUAWEI / Brand: HUAWEI / Model: DUB-LX1 / Hardware: qcom
[Android] Version: 8.1.0.170(C185) (REL)
[Clipious] Version: 1.19.5 Build: 40503

**Feedback:**
I don't  understand, what is the hash key

**Screenshot:**
![app screenshot](https://i.imgur.com/2Ah6xVT.png)

**Comment by lamarios** [comment]
I believe that it is an issue with invidious itself given that the comments don't show up on the web interface.
