### ISSUE TITLE
App is blank when opened

### ISSUE THREAD

**Issue by cuilean** [lamarios/clipious#532]
**Describe the bug**
When I open the app, it's blank except for the words "Could not Fetch the videos, tap to try again"

**To Reproduce**
1. Open Clipious
2. View the homepage 

**Expected behavior**
Videos should load on the homepage and searching for them shouldn't lead to the same error.

**Screenshots**
[
![Screenshot_20240420_085226](https://github.com/lamarios/clipious/assets/47678505/74b90166-ab5a-441b-a68e-882f60f069d6)
](url)

**Smartphone (please complete the following information):**
 - Samsung A71
 - Android 13
 - 1.19.5

**Additional context**
No other context needed.

**Comment by lamarios** [comment]
Are you using a public server , if yes please share ? If not public, did anything changed on your set up ?  This is an issue talking to an invidious server, there were no recent changes on that part of the application

**Comment by TheRouce** [comment]
I had this same issue, I just had to add a public server to the list. This should be included in some kind of onboarding, but seems like an improvement rather than a bug as the app does function once you add an endpoint for the invidious API.

**Comment by itoldusoandso** [comment]
Same thing here - Android 5.1
The LibreTube app plays fine though.

**Comment by lamarios** [comment]
Late reply on this. there was a but with this version where the setup wizard was not showing on first launch, it should be fixed by now.

```
Same thing here - Android 5.1
```
Android 5 is not supported
