### ISSUE TITLE
An version of clipious that fetches video directly from youtube servers

### ISSUE THREAD

**Issue by 2000prasanth** [lamarios/clipious#544]
I greatly appreciate the Clipious app, particularly its video filtering feature, which is a major factor in my continued use. However, there have been instances where the invidious server was unavailable, making the experience less reliable. I kindly suggest releasing another app with all of Clipious' features, but one that fetches requests directly from YouTube or pipe servers instead

**Comment by lamarios** [comment]
won't do.
