### ISSUE TITLE
[App Feedback] notconet 

### ISSUE THREAD

**Issue by ftservice** [lamarios/clipious#553]
**Runtime info:**
[Device] Manufacturer: Xiaomi / Brand: Xiaomi / Model: M2007J3SG / Hardware: qcom
[Android] Version: 12.V14.0.1.0.SJDMIXM (REL)
[Clipious] Version: 1.19.10 Build: 40553

**Feedback:**
notconet 

**Screenshot:**
![app screenshot](https://i.imgur.com/ciuzIHx.png)

**Comment by lamarios** [comment]
Not sure what to do with this.
