### ISSUE TITLE
delete downloads via long-press menu

### ISSUE THREAD

**Issue by chaserene** [lamarios/clipious#557]
**Is your feature request related to a problem? Please describe.**
deleting a download is not intuitive. the current way is to open the Downloads section and either swipe the entry left to the edge of the screen, or swipe partially and tap the appearing delete button. I’ve been wanting to do this but I was unable to figure it out until I found [your GitHub comment](https://github.com/lamarios/clipious/issues/262#issuecomment-1750112281) in which you explain this to another user who couldn’t figure it out.

**Describe the solution you'd like**
an additional and more intuitive way to delete would be to display a menu at the bottom of the screen when you long-press on a downloaded entry (both when you’re in the Home section and in the Downloads section), and have "Delete" as an option in that menu.

**Comment by lamarios** [comment]
There's now a "3 dots menu" in downloads
