### ISSUE TITLE
[App Feedback] over use of cell data even on data saver

### ISSUE THREAD

**Issue by MilanesaTM** [lamarios/clipious#560]
**Runtime info:**
[Device] Manufacturer: motorola / Brand: motorola / Model: Moto E (4) Plus / Hardware: mt6735
[Android] Version: 7.1.1.300 (REL)
[Clipious] Version: 1.19.10 Build: 40552

**Feedback:**
over use of cell data even on data saver

**Screenshot:**
![app screenshot](https://i.imgur.com/LSoz2g5.png)

**Comment by lamarios** [comment]
Reduce the video quality for lower bandwidth usage.
