### ISSUE TITLE
HTTP Basic authentication method

### ISSUE THREAD

**Issue by kkwpsi** [lamarios/clipious#564]
**Is your feature request related to a problem? Please describe.**
Not everyone exposes Invidious instance to the world. One of the security measures is HTTP Basic authentication.

**Describe the solution you'd like**
The application should determine whether additional authentication is required according to the HTTP Basic Auth rules. If so, the settings (login/password) saved in the application should be used.

**Comment by lamarios** [comment]
Fix will be in next release
