### ISSUE TITLE
[App Feedback] Videos don't load

### ISSUE THREAD

**Issue by vsl-iil** [lamarios/clipious#565]
**Runtime info:**
[Device] Manufacturer: OPPO / Brand: OPPO / Model: CPH1931 / Hardware: qcom
[Android] Version: 10.2022091100 (REL)
[Clipious] Version: 1.19.10 Build: 40553

**Feedback:**
Videos don't load; I'm connected to my local Invidious instance, and I checked that it works in browser. Previews and avatars are missing, too. Logs only show successful 200 codes.

**Screenshot:**
![app screenshot](https://i.imgur.com/LMcybek.png)

**Comment by lamarios** [comment]
Did you read this https://github.com/lamarios/clipious/wiki/Common-Issues#video-thumbnails-not-working ?

**Comment by matty-r** [comment]
Exact same issue here

**Comment by ViktorKahu** [comment]
Same issue here :(

Pixel 7 pro/a14 stock

Https://invidious.perennialte.ch

> Did you read this https://github.com/lamarios/clipious/wiki/Common-Issues#video-thumbnails-not-working ?

It can't be this because the same instance I use worked flawlessly up until recently. Now it works via the web browser, but not through clipious. Unless something changed recently either with the instance or the app.

**Comment by ViktorKahu** [comment]
Another interesting observation - unable to sign in using the cookie method - throws incorrect password or user name. The same password and user name work for the token.

**Comment by lamarios** [comment]
I tried this instance and it works fine for me. Did you updated to the version released yesterday? There was an issue with some instances not sending some data that was required.

**Comment by ViktorKahu** [comment]
> I tried this instance and it works fine for me. Did you updated to the version released yesterday? There was an issue with some instances not sending some data that was required.

Yeah, my bad, I was using an old version. Now works. Thank you for fixing it, your app is the best and has no alternatives for me.

**Comment by vsl-iil** [comment]
> Did you read this https://github.com/lamarios/clipious/wiki/Common-Issues#video-thumbnails-not-working ?

My bad, it seems that my instance isn't configured properly.

**Comment by lamarios** [comment]
No worries. I'll close this issue.
