### ISSUE TITLE
[App Feedback] could not fetch servers, tried reinstalling 

### ISSUE THREAD

**Issue by musowir** [lamarios/clipious#567]
**Runtime info:**
[Device] Manufacturer: Xiaomi / Brand: xiaomi / Model: Redmi Note 4 / Hardware: qcom
[Android] Version: 7.0.V11.0.2.0.NCFMIXM (REL)
[Clipious] Version: 1.19.10 Build: 40553

**Feedback:**
could not fetch servers, tried reinstalling, no hope.
![Screenshot_2024-07-22-17-41-47-651_com github lamarios clipious](https://github.com/user-attachments/assets/48e4d9e9-c5ad-4a32-9b5a-d4ea16981739)
 

**Screenshot:**
![app screenshot](https://i.imgur.com/sCr4H5g.png)

**Comment by lamarios** [comment]
Are you able to load this url on your phone?

https://api.invidious.io/instances.json?pretty=1&sort_by=type,users

**Comment by musowir** [comment]
Skippimg ssl certificate did work, thank you!

**Comment by lamarios** [comment]
This is most likely related to outdated android version.
