### ISSUE TITLE
Mismatch between Accrescent and F-Droid builds

### ISSUE THREAD

**Issue by CaseyBakey** [lamarios/clipious#568]
Hello,

I installed Clipious v1.9.11 (versionName), build 4056 (versionCode) from Accrescent.

I got an update notification from within F-Droid?

I accepted it, to see what would happen, pretty sure that it won't work.

But it did?!

F-Droid successfully installed v1.9.10 (versionName), build 40553 (versionCode).

It makes sense that this "downgrade" was possible because versionName can be whatever, but versionCode must be incremental.

However, how F-Droid was able to take precedence over Accrescent?

Clipious is now greyed out in Accrescent, and is updated through F-droid.

Are you the one providing signed APKs to F-Droid? That would also explain how the APK install did work (same signature).

Anyways, I guess you made a mistake regarding the versionCode.

Kind regards

**Comment by lamarios** [comment]
This is expected. Accrescent takes in an app bundle that share code between 3 architectures (arm v6 v6 and x86) under a single build number.

F droid uses split apks (one per architecture) and need different build numbers. The last digit is used to differentiate the architecture.

**Comment by CaseyBakey** [comment]
How about the signatures?

Are you the one providing signed APK to both Accrescent and F-Droid?

**Comment by lamarios** [comment]
Correct. In fdroid clipious is using the reproducible builds feature so signature should be the same. Though build numbers are different so you can't update an app installed from fdroid with the accrescent version for example.
