### ISSUE TITLE
[App Feedback] Despite uninstalling and reinatalling the app and changing instances, I am unable to load any videos. the thumbnails show up fine and I can even add the video to playlist but as soon as I go to watch a video I get this error. when I use the invidious instance in the browser it works perfectly.

### ISSUE THREAD

**Issue by SheepTD** [lamarios/clipious#569]
**Runtime info:**
[Device] Manufacturer: samsung / Brand: samsung / Model: SM-A127F / Hardware: exynos850
[Android] Version: 13.A127FXXSCDXE2 (REL)
[Clipious] Version: 1.19.10 Build: 40553

**Feedback:**
Despite uninstalling and reinstalling the app and changing instances, I am unable to load any videos. the thumbnails show up fine and I can even add the video to playlist but as soon as I go to watch a video I get this error. when I use the invidious instance in the browser it works perfectly.

**Screenshot:**
![app screenshot](https://i.imgur.com/bseMSkv.png)

**Comment by lamarios** [comment]
Are you using private instance? dash or standard stream? Are you using the proxy video setting?

**Comment by SheepTD** [comment]
I have tried:
inv.nadeko.net
and
inv.projectsegfau.lt
(Both public instances).

Dash and Proxy Video are both switched off.

**Comment by Gieted** [comment]
I'm having the same problem

**Comment by lamarios** [comment]
OK. I managed to reproduce on those instances. I'll need to do a deep dive to figure out what's going on.

**Comment by lamarios** [comment]
ok those instance are somehow missing fields when returning videos from the api. It looks like it runs a newer version of invidious than many other public servers. I'll push an update before more servers are at this version. Thanks for reporting

**Comment by lamarios** [comment]
next release will have the fix

**Comment by Gieted** [comment]
I can confirm that with update 1.19.12 the issue is now fixed 😄

BTW can you somehow make the app turn on PiP automatically when switching apps (like on yt premium)?
