### ISSUE TITLE
[App Feedback] Not able to play any video no matter what

### ISSUE THREAD

**Issue by Nyasper46** [lamarios/clipious#576]
**Runtime info:**
[Device] Manufacturer: vivo / Brand: vivo / Model: V2247 / Hardware: qcom
[Android] Version: 14.compiler06061713 (REL)
[Clipious] Version: 1.19.10 Build: 40553

**Feedback:**
Not able to play any video no matter what

**Screenshot:**
![app screenshot](https://i.imgur.com/nPyPDr4.png)

**Comment by lamarios** [comment]
Update the app

**Comment by lamarios** [comment]
Update the app

**Comment by ncarvalho99** [comment]
Runtime info:
[Device] Manufacturer: Xiaomi / Brand: POCO / Model: F5 / Hardware: qcom
[Android] Version: 14.
[Clipious] Version: 1.19.12

Feedback:
In the update 1.19.11 was not possible access even the video page, after the update i could access the video page but the video doesn't load

Screenshot:
![Screenshot_20240727-204703_Clipious](https://github.com/user-attachments/assets/eacbbfdf-2e7c-4e33-a571-855614574445)



> Update the app

**Comment by lamarios** [comment]
Are you hosting your own server?
If yes. Have you read this?
https://github.com/lamarios/clipious/wiki/Common-Issues

**Comment by ncarvalho99** [comment]
> Are you hosting your own server? If yes. Have you read this? https://github.com/lamarios/clipious/wiki/Common-Issues

Yes i'm hosting my own server.
I didn't read this, but after read, i made the right corrections and working now.

Thank you for your work and help

**Comment by Nyasper46** [comment]
> Update the app

Updated, still dont works in any video

**Comment by lamarios** [comment]
Which version are you on now?

**Comment by nbuechner** [comment]
Today's App update fixed playback for me on my instance.
