### ISSUE TITLE
Navigation bar invisible on android 14

### ISSUE THREAD

**Issue by anamitrapal** [lamarios/clipious#578]
**Describe the bug**
Navigation bar is not visible on Android 14.

**To Reproduce**
1. Open the app
2. See error

**Expected behavior**
Navigation bar should be visible in bottom

**Screenshots**
![photo_2024-07-28_21-42-18](https://github.com/user-attachments/assets/d998ad3d-1711-4ae7-8ef3-f290c5281021)

**Smartphone (please complete the following information):**
 - Device: Samsung S23
 - OS:  Android 14
 - Version : 14

**Additional context**
None

**Comment by lamarios** [comment]
Are you logged in to the server you're using?  If no then you're seeing what is expected.

**Comment by anamitrapal** [comment]
Navigation bar is visible after logging in.
