### ISSUE TITLE
[App Feedback] when I cliked on thumbnail this appeared

### ISSUE THREAD

**Issue by orl0pl** [lamarios/clipious#584]
**Runtime info:**
[Device] Manufacturer: motorola / Brand: motorola / Model: moto g72 / Hardware: mt6789
[Android] Version: 13.c5dbb-dbe37 (REL)
[Clipious] Version: 1.20.0 Build: 40583

**Feedback:**
when I cliked on thumbnail this appeared

**Screenshot:**
![app screenshot](https://i.imgur.com/7P4emk7.png)

**Comment by lamarios** [comment]
Most likely an issue with invidious itself as this would be an error message directly from it.

**Comment by orl0pl** [comment]
That's an instance issue. Closing issue.
