### ISSUE TITLE
[App Feedback] I can't watch some videos, I see this instead. Sometimes it says "Video details missing"

### ISSUE THREAD

**Issue by digitaldynastyjohn** [lamarios/clipious#585]
**Runtime info:**
[Device] Manufacturer: itel / Brand: Itel / Model: itel W5002 / Hardware: W5002
[Android] Version: 10.OP-V054-20220920 (REL)
[Clipious] Version: 1.20.0 Build: 40582

**Feedback:**
I can't watch some videos, I see this instead. Sometimes it says "Video details missing"

**Screenshot:**
![app screenshot](https://i.imgur.com/RgrbhMD.png)

**Comment by lamarios** [comment]
Please use the search function. Someone posted the exact same  problem.

Looks like an invidious problem.
