### ISSUE TITLE
[App Feedback] Stucks in any videos again lol

### ISSUE THREAD

**Issue by Nyasper46** [lamarios/clipious#586]
**Runtime info:**
[Device] Manufacturer: vivo / Brand: vivo / Model: V2247 / Hardware: qcom
[Android] Version: 14.compiler07172047 (REL)
[Clipious] Version: 1.20.0 Build: 40583

**Feedback:**
Stucks in any videos again lol

**Screenshot:**
![app screenshot](https://i.imgur.com/I37mWBG.png)

**Comment by lamarios** [comment]
Invidious issue.
