### ISSUE TITLE
[App Feedback] videolar yüklenmiyor 

### ISSUE THREAD

**Issue by senolfndk** [lamarios/clipious#595]
**Runtime info:**
[Device] Manufacturer: samsung / Brand: samsung / Model: SM-A217F / Hardware: exynos850
[Android] Version: 12.A217FXXSCDXE2 (REL)
[Clipious] Version: 1.21.2 Build: 40613

**Feedback:**
Videos are not loading 

**Screenshot:**
![app screenshot](https://i.imgur.com/wzsnDTE.png)

**Comment by lamarios** [comment]
It's an issue with invidious, YouTube is blocking  some of the public ones. Try different servers or host your own.
