### ISSUE TITLE
[Bug] when I click on a video, this happens

### ISSUE THREAD

**Issue by platformerr** [lamarios/clipious#597]
**Runtime info:**
[Device] Manufacturer: Nothing / Brand: Nothing / Model: A063 / Hardware: qcom
[Android] Version: 14.2407051617 (REL)
[Clipious] Version: 1.21.2 Build: 4061

**Feedback:**
when I click on a video, this happens

**Screenshot:**
![app screenshot](https://i.imgur.com/vzr7xwO.png)

**Comment by lamarios** [comment]
Issue with invidious. Use a different public instance or host it yourself.

**Comment by kr812** [comment]
I am also fetching this issue
![Uploading Screenshot_2024-12-16-23-40-10-713_com.github.lamarios.clipious.jpg…]()

**Comment by kr812** [comment]
How to use own server in clipous

**Comment by lamarios** [comment]
You can go to settings > manage server and tap the + bottom at the bottom right.
