### ISSUE TITLE
take back minsdk21 , android5.0 , please !

### ISSUE THREAD

**Issue by DI555** [lamarios/clipious#602]
Please , take back minsdk21 , android5.0 !
..or, at least, if not possible - just minsdk22 , android5.1 , please !
..we still have many devices on that.
i hope your build system support that!
Thank you very much in advance!

**Comment by lamarios** [comment]
Sorry I can't support it. It is 10 years old at this point.

**Comment by lamarios** [comment]
One of the libraries I use to do something highly requested needs min SDK 24.
