### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by nsoolo** [lamarios/clipious#603]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A timer where you can select a specific amount of time before the video is automaticaally paused.

**Describe alternatives you've considered**
None

**Additional context**
Nothing else to add

**Comment by lamarios** [comment]
Will be in next release.

[Screencast from 2024-09-28 13-12-46.webm](https://github.com/user-attachments/assets/290169ff-2741-4820-868f-a7fe64fd9a9a)

![Screenshot from 2024-09-28 13-04-56](https://github.com/user-attachments/assets/b84b1547-5b31-4975-82b5-7f6c77ab04ed)
