### ISSUE TITLE
Screen controls

### ISSUE THREAD

**Issue by anoo2niem** [lamarios/clipious#604]
Hi,

First of all thanks for your hard work!

I have both an invidious instance and a piped instance, and use both android apps clipious & libretube respectively.
I tend to switch between both, and there is one thing i find actually very valuable on libretube which is currently not supported yet with clipious; screen controls.

There are 3 functions i would like to suggest;

1) Swipe up/down on left half on screen > adjust volume respectively

![e22c979d-c086-40fc-94cd-e3b8e587c751](https://github.com/user-attachments/assets/44e1fc6b-a701-449c-8b6d-3a82853f4a02)

2) Swip up/down on right half on screen > adjust brightness respectively

![a2678a30-90ec-4ba6-ba93-2a3042b4ef09](https://github.com/user-attachments/assets/901d3041-9d58-4f7b-a3c9-dd2d73855793)

3) Pinch-to-zoom, touch the screen with two fingers and move them together or apart to zoom in or out. > zoom in would be adjust video to fullscreen, zoom out would be default aspect ratio.

![021cf059-edbf-414a-a778-867bb8be776e](https://github.com/user-attachments/assets/cd4e820c-5c30-4b0c-8ccc-38bee842f77d)

Obviously this is just a suggestive enhancement with 0 urgence, as i do understand this is an opensource project and putting time in enhancements is probably no priority.

I would like to thank u again for your time & efforts putted in this project.

**Comment by lamarios** [comment]
Will be in then ext release 
[Screencast from 2024-09-28 17-52-02.webm](https://github.com/user-attachments/assets/6b74ee98-48d8-40e9-bc4d-a82331ca3588)

**Comment by anoo2niem** [comment]
Wow that was fast...

Many thanks!

**Comment by lamarios** [comment]
Most welcome, I had time to work on some simple features this week end

**Comment by Caliv0** [comment]
Hey, love your app. It's by far the most used one on my phone.

Whilst I like this new feature I find myself constantly triggering it by mistake and thus blinding myself at night and/or defening myself. Would be great if I could disable it in the settings.

**Comment by anoo2niem** [comment]
I do love the feature, as i requested it, but i have to agree i accedentally trigger volume or brightness aswell sometimes.
If the 'sensitivity' could be dialed down, it would be awesome. 
Compared to libretube now it is hyper sensitive currently.

Many thanks!

**Comment by lamarios** [comment]
yeah it happened to me few times.

I'll update it so that the dragging is relative to the current value (brightness or volume) instead of the position of the finger on the screen.

I'll also add a buffer so it only start adjusting after moving a minimum amount

**Comment by lamarios** [comment]
Will be in releas 1.22.2

**Comment by Caliv0** [comment]
Works perfectly, thank you!
