### ISSUE TITLE
Feature : subtitles font size

### ISSUE THREAD

**Issue by AceDenghar** [lamarios/clipious#61]
First of all : What a great app ! Thanks ☺️

Would it be possible to add a setting to modify subtiles size ?

On my tablet (11") they are very small.

Sorry for my english ^^

Thanks

**Comment by lamarios** [comment]
Will be in the next release in the app settings

![image](https://user-images.githubusercontent.com/1192563/232015376-c8dec915-4edb-4eee-8697-c0f0952395f6.png)

**Comment by AceDenghar** [comment]
Good Job,

It's perfect !

Thank you 🤟

**Comment by AceDenghar** [comment]
Oh ! Maybe a suggest :

Instead of setting a fixed size : could it be a percentage of the width of the current vidéo ?

**Comment by lamarios** [comment]
Don't think it's easily doable.
