### ISSUE TITLE
Incorrect handling of premieres

### ISSUE THREAD

**Issue by highda** [lamarios/clipious#610]
**Describe the bug**
Clipious doesn't fetch the right information from Invidious when the video hasn't premiered yet.

**To Reproduce**
1. Subscribe to a channel, or open a channel that has an upcoming premiere on Invidious
2. Check the video's upload time in Invidious
3. Check the same video's upload time in Clipious

**Expected behavior**
The time section should show the premiere time, just like Invidious:
![{860E873D-A858-4683-B08C-597FAA2C9282}](https://github.com/user-attachments/assets/eaef9b89-90bd-469a-b297-d24b6038e1c2)

**Screenshots**
![Screenshot_20240929-150355_Clipious](https://github.com/user-attachments/assets/28d07103-8bbf-4567-b3bc-d208181ee811)
Clipious shows a video uploaded 20hrs ago.

**Comment by lamarios** [comment]
Will be in release 1.22.2
