### ISSUE TITLE
Sound-only with live streams

### ISSUE THREAD

**Issue by MrQubo** [lamarios/clipious#611]
**Describe the bug**

The sound-only switch isn't working with live streams. After switching to sound-only live streams gets paused after a few seconds.

**To Reproduce**
1. Go to this video: https://www.youtube.com/watch?v=jfKfPfyJRdk
2. Start the video.
3. Click on the small note under the video (left side).
4. Wait a few seconds.

(Steps 2. and 3. can also be done in the reverse order)

**Expected behavior**
Live stream doesn't get paused.

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: GrapheneOS (Android 14)
 - Build number: 2024091900

**Comment by lamarios** [comment]
I should probably disable the switch for live streams. I don't believe your provided an audio only stream for live.

**Comment by MrQubo** [comment]
Yes, the live stream I linked is not audio-only, which is the point. The switch works for normal video, not live streams. It plays just audio without playing video.

**Comment by lamarios** [comment]
Will be in release 1.22.2
