### ISSUE TITLE
Trust self-signed SSL certs

### ISSUE THREAD

**Issue by ddscentral** [lamarios/clipious#620]
**Is your feature request related to a problem? Please describe.**
I have an private Invidious instance without public access that I wish to use SSL with. However, currently it's not possible to use it in Clipious as there's no way to trust self-signed certs.

**Describe the solution you'd like**
Ability to trust the currently used SSL certificate eg.  by storing it's modulus (that is, pinning it to a specific instance). This would not compromise SSL while allowing self-signed certificates to be used.
There are examples of this, e.g. Proxmox VE Backup server client.

**Describe alternatives you've considered**
Use a "real" hostname (something which can be resolved publicly) mapped to an internal IP and use a publicly trusted certificate for SSL. This is doable but very cumbersome to setup due to the way my instance is hosted.

**Additional context**

**Comment by lamarios** [comment]
The SSL verification skip does not work for you ?

**Comment by ddscentral** [comment]
I cannot add the server, the app says the server is invalid and shows a certificate error.
Is there an option already ? I did look but I could not find one.

**Comment by lamarios** [comment]
![Uploading Screenshot_20241016-184252~2.png…]()

**Comment by ddscentral** [comment]
Silly me, it was right above the list, didn't notice.
Sorry for bothering you.

**Comment by lamarios** [comment]
Yeah it is not an ideal way of doing this I have to agree. But it was the quickest to implement last time. 

Glad that it works now.
