### ISSUE TITLE
bug. With a long title the eye and the date start to be behind the preview of another video

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#63]
With a long title the eye and the date start to be behind the preview of another video
![342058.jpg](https://user-images.githubusercontent.com/113500363/225975156-792c79e6-9ad1-4a77-a502-0493e24f2720.jpg)

**Comment by lamarios** [comment]
Last release limited the title to one line only, this shouldn't happen anymore

**Comment by lamarios** [comment]
reverted back to 2 lines
