### ISSUE TITLE
Error in some thumbnails, olay and downloads.

### ISSUE THREAD

**Issue by ManuXD32** [lamarios/clipious#636]
**Describe the bug**
First of all I wanna say that it is not the typical issue with the thumbnails, as it is configured as suggested and clipious doesn't throw an error when adding my server.

When I access clipious some videos show their thumbnail and some of them show an image with an exclamation. 
![ResizedImage_2024-11-11_16-46-39_2343.jpg](https://github.com/user-attachments/assets/908c7572-cd90-4150-aa1f-baf4fc01c5de)

Those that show the exclamation keep trying to load but never play and cannot be downloaded (they keep trying but never download).

I have tried to watch them directly on invidious and there is no problem with those videos using the Invidious instance.

**To Reproduce**
1. Go to the app
2. Scroll down and find a video with an exclamation per thumbnail.
3. See error

**Expected behavior**
The thumbnail shows, the video plays and can be downloaded.

**Smartphone (please complete the following information):**
 - Device: Redmagic 9S pro, samsung galaxy tab s6 lite and MiBox
 - OS: Android 14, Android 13 and Android 9
 - Version 1.22.2

**Comment by hatredholder** [comment]
can confirm, having the same weird issue - no problem playing videos on invidious, but some thumbnails/videos aren't loading on clipious

**Comment by lamarios** [comment]
I'm facing the same problem but i don't known when I will have time to fix it.  If any one has the courage to make a PR it will be greatly appreciated.

**Comment by ManuXD32** [comment]
> I'm facing the same problem but i don't known when I will have time to fix it. If any one has the courage to make a PR it will be greatly appreciated.

Wish I had the knowledge to do that haha.
Sorry if I sounded like I was demanding an immediate fix, just wanted to let you know. 
Thanks for taking the time ton answer :)

**Comment by lamarios** [comment]
Oh no. Don't worry. That's not how took it. It was just a note to say I won't have much time to fix that soon :)

**Comment by ManuXD32** [comment]
> Oh no. Don't worry. That's not how took it. It was just a note to say I won't have much time to fix that soon :)

Oh okay :)

**Comment by technoplayer** [comment]
I have the same issue and I have noticed that Invidious web is requesting `mqdefault.jpg` for the thumbnail, but Clipious is requesting `maxres.jpg`. 

I have no issue playing the video, it's just the thumbnail.

**Comment by madeofpendletonwool** [comment]
Good find @technoplayer. I suspect then that the issue could be with this in video.dart

  ImageObject? getBestThumbnail() {
    if (videoThumbnails.isNotEmpty) {
      return videoThumbnails
          .firstWhere((element) => element.quality == 'maxres');
    } else {
      return null;
    }
  }
}

I think potentially falling back the mqdefault.jpg might fix it?

ImageObject? getBestThumbnail() {
    if (videoThumbnails.isEmpty) return null;
    
    // Try maxres first
    try {
      return videoThumbnails.firstWhere((element) => element.quality == 'maxres');
    } catch (_) {
      // Try mqdefault second
      try {
        return videoThumbnails.firstWhere((element) => element.quality == 'mqdefault');
      } catch (_) {
        // Fall back to first available thumbnail
        return videoThumbnails.first;
      }
    }
}

I don't currently have a build environment setup to test that theory but I think that could be a good place to start. I'll try and get something setup a little later today to test that.

**Comment by lamarios** [comment]
Great find thanks ! I should have the time to look into it before the end of the week.

**Comment by AceDenghar** [comment]
Thanks for all your job guys 👍

**Comment by lamarios** [comment]
version 1.22.3 is on the way and should fix the issue

**Comment by hatredholder** [comment]
> version 1.22.3 is on the way and should fix the issue

still no release on f-droid?

**Comment by lamarios** [comment]
Could it be because of this ? https://github.com/lamarios/clipious/issues/638 

I'll try to remember to check it out over the week end.

**Comment by hatredholder** [comment]
> Could it be because of this ? #638
> 
> I'll try to remember to check it out over the week end.

i'll make sure to remind you on saturday :)
