### ISSUE TITLE
[App Feedback] AUDIOTRACK DISABLER OR CHANGER!!!

### ISSUE THREAD

**Issue by Bounzzer** [lamarios/clipious#640]
**Runtime info:**
[Device] Manufacturer: Google / Brand: google / Model: Pixel 6 Pro / Hardware: raven
[Android] Version: 15.2024111800 (REL)
[Clipious] Version: 1.22.3 Build: 40663

**Feedback:**
AUDIOTRACK DISABLER!
Audio is in Wrong Langue

**Screenshot:**
![app screenshot](https://i.imgur.com/lZviS4q.png)

**Comment by lamarios** [comment]
It's an issue with invidious: https://github.com/iv-org/invidious/issues/2007

**Comment by Bounzzer** [comment]
It a over 3 Year Old Theard whitch no Help inside
