### ISSUE TITLE
Aborting and removing a video from the download list

### ISSUE THREAD

**Issue by robovoice1** [lamarios/clipious#642]
**Is your feature request related to a problem? Please describe.**

I accidently tapped for a video download with the highest resolution. The downloaded size would have been about 5GB.
Once the download started, i could not stop and remove this video download from the download list. 
Force stopping the whole app interrupts the download, but after restarting and tapping on the video the download starts again from the beginning (loop)
To get the video from the list i re-installed the app.

**Describe the solution you'd like**

A possibility/selection to stop and remove a started video download.

**Describe alternatives you've considered**
None

**Additional context**

On a wifi network this feature is not so relevant, but on metered networks.
One video download (with highest resolution) can be the reason to have used all of your booked " high speed internet".

Thanks.

**Comment by lamarios** [comment]
fix will be in the new version 1.22.4
