### ISSUE TITLE
add "subscribe" and "add to playlist" buttons somewhere near the video preview

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#65]
I immediately understand that it should be in the playlist, and I do not want to do unnecessary actions. 

![342064.jpg](https://user-images.githubusercontent.com/113500363/225978320-65fcb968-b708-487a-8179-e02f2a16341e.jpg)

**Comment by lamarios** [comment]
I don't think I want to do this one. I don't want the ui to be too cluttered.

**Comment by lamarios** [comment]
the add to playlist via long press is going to be released on v1.7.17
