### ISSUE TITLE
Invidious API Lockdown - Change user agent

### ISSUE THREAD

**Issue by Sommerwiesel** [lamarios/clipious#653]
**Is your feature request related to a problem? Please describe.**
I am the maintainer of invidious.nerdvpn.de.
All public instances, including mine, have locked down the Invidious API from public use.
Here is a (good) statement about the reasons from one of the other maintainers: https://git.nadeko.net/Fijxu/invidious/wiki/Important-information

**Describe the solution you'd like**
A quick fix that you could deploy right now is:
Change Clipious user agent from "Dart/3.5 (dart:io)" to something we can _somewhat safely_ whitelist so that Clipious can use the public instances APIs again.
I.e. Change "Dart/3.5 (dart:io)" to "Clipious/1.22.5 (com.lamarios.clipious)" or similar.

**Describe alternatives you've considered**
Alternatives are the already included basic auth but that would require any user to know the API credentials and thus is not usable in this situation.

I'm also working on whitelisting any request that comes from a user that is already authenticaten in Invidious via token auth but this will take a while.
Until then, changing user agent seems to be the best quick fix for this.

You can also contact me on Matrix under @weidenwiesel:nerdvpn.de if you want to talk about other solutions.

Cheers.

**Comment by lamarios** [comment]
will make a small release with a fix for this.


![image](https://github.com/user-attachments/assets/c80e6d34-c4e6-4df8-ac68-370c20e3c9ba)
