### ISSUE TITLE
add a pause button and make the <- and -> buttons work (at this point they don't)

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#66]
![342075.jpg](https://user-images.githubusercontent.com/113500363/225980090-eb9d8644-fb12-420e-b081-429803d9a3df.jpg)

**Comment by lamarios** [comment]
Probably won't be done in the near future. I'm using a library that handles this and it's handling of playlists is not great. I'd have to either modify the library or re-do the player using a more barebone player and implement all the options myself.
