### ISSUE TITLE
Feature request. Change the icon if a video has already been added to the playlist

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#68]
If a video is already added to a playlist, change the icon from + to something else

when clicked, the same thing should happen as it did before adding this icon

![342085.jpg](https://user-images.githubusercontent.com/113500363/225983189-b10b73f4-3c88-4491-98d3-8e2bd3ac45cc.jpg)

**Comment by lamarios** [comment]
![image](https://user-images.githubusercontent.com/1192563/226886326-a5ed93aa-7367-4be4-93d6-f904da6fa63c.png)
Added an indicator to show the number of playlists a video is into

also disabled the button if the video is already in a  playlist.
![image](https://user-images.githubusercontent.com/1192563/226886620-1bfd57a6-e38f-4caa-aed8-d5a6ff20b51a.png)

**Comment by lamarios** [comment]
will be on the next release when it's ready
