### ISSUE TITLE
Question: Tablet UI

### ISSUE THREAD

**Issue by RAVENz46** [lamarios/clipious#71]
Thank you for your efforts in developing the app.

I set my phone's smallest width 600 in developer option, so other apps show tablet UI but it doesn't.
So my question is how does this app distinguish between a smartphone and a tablet?
Is it possible to force tablet UI on smartphone?

Thank you.

**Comment by lamarios** [comment]
Hi,

The code to check whether it is a tablet is [here](https://github.com/lamarios/clipious/blob/master/lib/utils.dart#L103). It basically checks the smallest side of a device, if it is < 600 it is a phone if not a tablet.

I'm not sure how the width is reported by flutter when the user modify the developer options.

**Comment by RAVENz46** [comment]
I see. Thank you very much.
