### ISSUE TITLE
Sorry for creating so many issues

### ISSUE THREAD

**Issue by Wjxfi** [lamarios/clipious#72]
Maybe because of me you stopped frequent development, because you thought that so many requests are too difficult to fulfill, or you coded often because of me and got tired, I'm very sorry

I really didn't want that to happen😔

**Comment by lamarios** [comment]
Hey!

I'm not going to lie it was a bit scary to see so many issues in such a short time but development didn't stop.

I'm working on some big refactoring of the code to make future development easier and testable (if I ever get the courage write unit tests) and I won't make any other releases until I'm done with it. I'm also on holiday this week. 😊

Though it doesn't mean I will implement every single issues raised. I have my own goals for the app and the main one is to keep it fairly simple. I don't want to fall in the trap of making every single part of it configurable and it then becomes a nightmare to maintain.

**Comment by AceDenghar** [comment]
Hey, don't be afraid, it's a good things to have suggest, you don a good job 👍

Take what you want without stress, we can wait, but we are excited by your app we waited for so long.

PS : sorry for my english (i'm french and may could help for translation)
