### ISSUE TITLE
Continuous playback in mini-player

### ISSUE THREAD

**Issue by dvcky** [lamarios/clipious#73]
Hi! Really loving the app so far, keep it up! That being said, I feel like the application might feel a bit less clunky if the playback doesn't reload when you swipe the player in or out of the mini player. Is this possible?

**Comment by lamarios** [comment]
Thanks for the feedback. I agree with you. I need to find a better way to handle this.

I think I should have a single "page" for playing videos but that would drastically change the way navigation works within the app and edge cases that might go along with it.

I should probably download some other apps like the actual YouTube app and free tube to see how they handle this.

**Comment by lamarios** [comment]
I revamped the whole video player flow of the app, now there's a single player for the whole app so it is less clunky, with possibility to add video to the queue or play from scratch. Shuffle, repeat is also handled

Uploading screen-20230402-113623 (trimmed)(1).mp4…

**Comment by lamarios** [comment]
actually released :)

**Comment by dvcky** [comment]
> I revamped the whole video player flow of the app, now there's a single player for the whole app so it is less clunky, with possibility to add video to the queue or play from scratch. Shuffle, repeat is also handled
> 
> Edit: I'm having issues with uploading the video here so here's a peertube link: https://peertube.fioverse.zone/w/sm4LBVByrLxz8pnrfFEEFC
> 
> Will be released soon hopefully. Couple of small issues to fix

Wow, amazing work! Thank you so much!

**Comment by lamarios** [comment]
Thanks :) it's still not perfect (few bugs here and there) and I did some ugly workaround to make some stuff work. I think I need deeper flutter knowledge to tackle those ugly things.
