### ISSUE TITLE
Granular Sponsorblock Support

### ISSUE THREAD

**Issue by matchboxbananasynergy** [lamarios/clipious#79]
Currently, it seems that Sponsorblock support comes in the form of one on/off toggle.

It also seems that when it is turned on, only `Sponsor` segments are skipped, and none of all the others ones.

If possible, it would be great to be able to have granular control over which kinds of segments are skipped, and which are not, as well as enabling other kinds of segments like Interaction reminders or non-music sections.

**Comment by lamarios** [comment]
Release in 1.6.0
