### ISSUE TITLE
Distraction free mode

### ISSUE THREAD

**Issue by MintMain21** [lamarios/clipious#9]
This is a very impressive client right out of the gate. 

Here are some options I think would be neat....

Option to use DASH Quality

Option to hide distractions (Trending, Comments, etc)

Option to play videos in the background or through PiP. 

Option to follow channels or save playlists without an account (saved locally in the app itself)

**Comment by lamarios** [comment]
Thanks for the feedback. Those are good inrpovements. 

 I'll look into it.


Though for the dash currently YouTube is throttling those from what I've seen on invidious issues. I still can add back a way to use it.

**Comment by lamarios** [comment]
For the remaining two
Local playlists / subscriptions: won't do, that's the whole point of using something like invidious.

Removing tabs: also won't do. The extra tabs are harmless as you can select which tab the app starts on.
