### ISSUE TITLE
Share video while watching it with optional current timestamp

### ISSUE THREAD

**Issue by dln949** [lamarios/clipious#98]
Can a standard share button be added?  Also, ability to copy URL of video at a certain time?

**Comment by lamarios** [comment]
There's a share button already. Where youhave to choose between the invidious or YouTube   url

The share button on the top bar

![Screenshot_20230406-213828.png](https://user-images.githubusercontent.com/1192563/230395601-8b7b4635-1c9e-4db7-9e0e-4b4f7a76ba18.png)


Then there's the standard sharing sheet. 

![Screenshot_20230406-213903~2.png](https://user-images.githubusercontent.com/1192563/230395973-5b30386a-0d4c-4d5d-8fe3-bfc26f9fb15e.png)


I'll look into sharing the specific time of a video.

**Comment by dln949** [comment]
Thank you.  

Regarding the existing share button:  Yes, you are right, but I failed to make myself clear.  I meant, Can the share button conveniently also appear on the screen while I'm watching the video, instead of only on the screen before I start playing the video?

**Comment by lamarios** [comment]
yeah that's a good idea. I'll change the ticket title
